/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/jurisdictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jurisdictions */
        get: operations["jurisdictions_api_v1_metadata_jurisdictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_api_v1_metadata_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metadata/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products */
        get: operations["products_api_v1_metadata_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/knowledge-scope": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Scope */
        get: operations["project_scope_api_v1_projects__project_id__knowledge_scope_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/knowledge/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retrieve */
        post: operations["retrieve_api_v1_projects__project_id__knowledge_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/retrieval-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieval Run */
        get: operations["retrieval_run_api_v1_retrieval_runs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evidence-packs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence Pack */
        get: operations["evidence_pack_api_v1_evidence_packs__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge-sufficiency/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sufficiency */
        get: operations["sufficiency_api_v1_knowledge_sufficiency__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/knowledge-versions/{id}/runtime-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime Readiness */
        get: operations["runtime_readiness_api_v1_admin_knowledge_versions__id__runtime_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** KnowledgeScope */
        KnowledgeScope: {
            /** Tenant Id */
            tenant_id: string;
            /** Project Id */
            project_id: string;
            /** Analysis Snapshot Id */
            analysis_snapshot_id?: string | null;
            /** Subject Type */
            subject_type: string;
            /** Subject Id */
            subject_id: string;
            /**
             * Allowed Jurisdiction Ids
             * @default []
             */
            allowed_jurisdiction_ids: string[];
            /**
             * Allowed Product Domain Ids
             * @default []
             */
            allowed_product_domain_ids: string[];
            /**
             * Allowed Product Category Ids
             * @default []
             */
            allowed_product_category_ids: string[];
            /**
             * Allowed Product Family Ids
             * @default []
             */
            allowed_product_family_ids: string[];
            /**
             * Allowed Product Ids
             * @default []
             */
            allowed_product_ids: string[];
            /**
             * Allowed Product Tag Ids
             * @default []
             */
            allowed_product_tag_ids: string[];
            /**
             * Allowed Scenario Ids
             * @default []
             */
            allowed_scenario_ids: string[];
            /**
             * Allowed Industry Refs
             * @default []
             */
            allowed_industry_refs: string[];
            /**
             * Allowed Data Category Refs
             * @default []
             */
            allowed_data_category_refs: string[];
            /** Allowed Scope Types */
            allowed_scope_types: string[];
            /** Permission Filters */
            permission_filters: string[];
            /** Lifecycle Filters */
            lifecycle_filters: string[];
            /**
             * Effective As Of
             * Format: date
             */
            effective_as_of: string;
            /** Excluded Bindings */
            excluded_bindings: {
                [key: string]: unknown;
            }[];
            /** Unresolved Scopes */
            unresolved_scopes: string[];
            /** Reason Codes */
            reason_codes: string[];
            /** Review Required */
            review_required: boolean;
            /** Version */
            version: number;
            filter_spec: components["schemas"]["KnowledgeFilterSpec"];
        };
        /** KnowledgeFilterSpec */
        KnowledgeFilterSpec: {
            /** Tenant Filter */
            tenant_filter: string;
            /** Permission Filter */
            permission_filter: string[];
            /** Lifecycle Filter */
            lifecycle_filter: string[];
            /**
             * Effective Date Filter
             * Format: date
             */
            effective_date_filter: string;
            /** Jurisdiction Filter */
            jurisdiction_filter: string[];
            /** Product Filter */
            product_filter: {
                [key: string]: string[];
            };
            /** Scenario Filter */
            scenario_filter: string[];
            /** Industry Filter */
            industry_filter: string[];
            /** Data Category Filter */
            data_category_filter: string[];
            /** Language Filter */
            language_filter: string[];
            /** Scope Type Filter */
            scope_type_filter: string[];
            /** Version Filter */
            version_filter: string[];
            /** Binding Filter */
            binding_filter: string[];
            /**
             * Filter Order
             * @default [
             *       "tenant",
             *       "permission",
             *       "lifecycle",
             *       "version",
             *       "effective_date",
             *       "product",
             *       "jurisdiction",
             *       "scenario",
             *       "industry",
             *       "data_category",
             *       "language"
             *     ]
             */
            filter_order: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** RetrievalRequestDTO */
        RetrievalRequestDTO: {
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Policy Id
             * Format: uuid
             */
            policy_id: string;
            /** Query Text */
            query_text: string;
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Subject Type
             * @default PROJECT
             * @enum {string}
             */
            subject_type: "PROJECT" | "DATA_ITEM" | "DATA_FLOW";
            /** Subject Id */
            subject_id?: string | null;
            /**
             * Languages
             * @default []
             */
            languages: string[];
        };
        /** RetrievalResponseDTO */
        RetrievalResponseDTO: {
            /** Retrieval Run Id */
            retrieval_run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING" | "COMPLETED" | "FAILED";
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Traces */
            traces: components["schemas"]["RetrievalTrace"][];
            statistics: components["schemas"]["RetrievalStatistics"];
            /** Record Version */
            record_version: number;
            rag_context_pack: components["schemas"]["RAGContextPack"] | null;
        };
        /** RetrievalTrace */
        RetrievalTrace: {
            /** Stage */
            stage: string;
            /** Reason Code */
            reason_code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** RetrievalStatistics */
        RetrievalStatistics: {
            /**
             * Lexical Count
             * @default 0
             */
            lexical_count: number;
            /**
             * Vector Count
             * @default 0
             */
            vector_count: number;
            /**
             * Deduplicated Count
             * @default 0
             */
            deduplicated_count: number;
            /**
             * Reranked Count
             * @default 0
             */
            reranked_count: number;
            /**
             * Dropped Count
             * @default 0
             */
            dropped_count: number;
            /**
             * Internal Evidence Count
             * @default 0
             */
            internal_evidence_count: number;
            /**
             * External Evidence Count
             * @default 0
             */
            external_evidence_count: number;
        };
        /** RAGContextPack */
        RAGContextPack: {
            structured_context: components["schemas"]["FormalContext"];
            scope: components["schemas"]["KnowledgeScope"];
            evidence_pack: components["schemas"]["EvidencePack"];
            knowledge_sufficiency: components["schemas"]["KnowledgeSufficiencyResult"];
            /** External Augmentation Metadata */
            external_augmentation_metadata: {
                [key: string]: unknown;
            };
            fallback_guidance_context?: components["schemas"]["ActionableFallbackGuidanceContext"] | null;
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
            /**
             * Legal Decision
             * @default false
             * @constant
             */
            legal_decision: false;
        };
        /** FormalContext */
        FormalContext: {
            /** Project Id */
            project_id: string;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "PROJECT" | "DATA_ITEM" | "DATA_FLOW";
            /** Subject Id */
            subject_id: string;
            /** Context Version */
            context_version: number;
            /** Dimensions */
            dimensions: {
                [key: string]: string[];
            };
            /** Product Unresolved */
            product_unresolved: boolean;
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /**
             * System Ids
             * @default []
             */
            system_ids: string[];
            /**
             * Party Ids
             * @default []
             */
            party_ids: string[];
            /**
             * Product Lineages
             * @default {}
             */
            product_lineages: {
                [key: string]: {
                    [key: string]: string[];
                };
            };
        };
        /** EvidencePack */
        EvidencePack: {
            /** Evidence Pack Id */
            evidence_pack_id: string;
            /** Retrieval Run Id */
            retrieval_run_id: string;
            /** Analysis Snapshot Id */
            analysis_snapshot_id: string;
            /** Items */
            items: components["schemas"]["EvidencePackItem"][];
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
            /**
             * Legal Source Of Truth
             * @default false
             * @constant
             */
            legal_source_of_truth: false;
        };
        /** EvidencePackItem */
        EvidencePackItem: {
            /** Evidence Item Id */
            evidence_item_id: string;
            /** Knowledge Document Id */
            knowledge_document_id?: string | null;
            /** Knowledge Version Id */
            knowledge_version_id?: string | null;
            /** External Evidence Id */
            external_evidence_id?: string | null;
            /** Structure Node Id */
            structure_node_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Citation Id */
            citation_id: string;
            /** Source Id */
            source_id: string;
            /** Source Url */
            source_url: string;
            /** Source Authority */
            source_authority?: string | null;
            /**
             * Source Tier
             * @enum {string}
             */
            source_tier: "T1_PRIMARY_OFFICIAL" | "T2_OFFICIAL_GUIDANCE" | "T3_INTERGOVERNMENTAL" | "T3_APPROVED_SECONDARY" | "T4_UNVERIFIED_WEB" | "T4_LLM_DISCOVERY_ONLY";
            /** Jurisdiction Id */
            jurisdiction_id?: string | null;
            /**
             * Jurisdiction Specific
             * @default false
             */
            jurisdiction_specific: boolean;
            /** Canonical Locator */
            canonical_locator: string;
            /** Language */
            language: string;
            /** Effective From */
            effective_from?: string | null;
            /** Effective To */
            effective_to?: string | null;
            /** Lexical Score */
            lexical_score?: number | null;
            /** Vector Score */
            vector_score?: number | null;
            /**
             * Hybrid Score
             * @default 0
             */
            hybrid_score: number;
            /** Rerank Score */
            rerank_score?: number | null;
            /**
             * Scope Validation Status
             * @default VALIDATED
             * @constant
             */
            scope_validation_status: "VALIDATED";
            /** Evidence Quality */
            evidence_quality: number;
            /** Content Hash */
            content_hash: string;
            /** Retrieval Run Id */
            retrieval_run_id: string;
            /** Analysis Snapshot Id */
            analysis_snapshot_id: string;
            /** Knowledge Index Version */
            knowledge_index_version?: string | null;
            /** Retrieval Policy Version */
            retrieval_policy_version: string;
            /** Original Text */
            original_text: string;
            /**
             * Topic Refs
             * @default []
             */
            topic_refs: string[];
            /**
             * Regulation Refs
             * @default []
             */
            regulation_refs: string[];
            /** Conflict Key */
            conflict_key?: string | null;
            /** Claim Hash */
            claim_hash?: string | null;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
            /**
             * Legal Decision
             * @default false
             * @constant
             */
            legal_decision: false;
        };
        /** KnowledgeSufficiencyResult */
        KnowledgeSufficiencyResult: {
            /** Sufficiency Result Id */
            sufficiency_result_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Project Id */
            project_id: string;
            /** Analysis Snapshot Id */
            analysis_snapshot_id: string;
            /** Subject Type */
            subject_type: string;
            /** Subject Id */
            subject_id: string;
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            /** Retrieval Run Id */
            retrieval_run_id: string;
            /** Evidence Pack Id */
            evidence_pack_id: string;
            /** Jurisdiction Coverage */
            jurisdiction_coverage: {
                [key: string]: boolean;
            };
            /** Regulation Coverage */
            regulation_coverage: {
                [key: string]: boolean;
            };
            /** Official Source Coverage */
            official_source_coverage: number;
            /** Effective Date Coverage */
            effective_date_coverage: number;
            /** Evidence Quality */
            evidence_quality: number;
            /** Evidence Count */
            evidence_count: number;
            /** Conflicting Evidence Count */
            conflicting_evidence_count: number;
            /** Missing Topics */
            missing_topics: string[];
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: number;
            /** Review Required */
            review_required: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "SUFFICIENT" | "PARTIALLY_SUFFICIENT" | "INSUFFICIENT" | "CONFLICTED";
            /** Policy Version */
            policy_version: string;
        };
        /** ActionableFallbackGuidanceContext */
        ActionableFallbackGuidanceContext: {
            /**
             * Verified Requirements
             * @default []
             */
            verified_requirements: string[];
            /**
             * Verified Controls
             * @default []
             */
            verified_controls: string[];
            /** Conservative Controls */
            conservative_controls: components["schemas"]["GuidanceAction"][];
            /** Evidence Acquisition Steps */
            evidence_acquisition_steps: components["schemas"]["GuidanceAction"][];
            /** Jurisdiction Verification Steps */
            jurisdiction_verification_steps: components["schemas"]["GuidanceAction"][];
            /** Unresolved Legal Questions */
            unresolved_legal_questions: string[];
            /** Operational Next Steps */
            operational_next_steps: components["schemas"]["GuidanceAction"][];
            /** Prohibited Assertions */
            prohibited_assertions: string[];
            /**
             * Evidence Status
             * @enum {string}
             */
            evidence_status: "SUFFICIENT" | "PARTIALLY_SUFFICIENT" | "INSUFFICIENT" | "CONFLICTED";
            /** Confidence */
            confidence: number;
            /**
             * Review Recommended
             * @default true
             */
            review_recommended: boolean;
            /**
             * Finalization Requires Verification
             * @default true
             * @constant
             */
            finalization_requires_verification: true;
            /**
             * Compliance Path
             * @default false
             * @constant
             */
            compliance_path: false;
        };
        /** GuidanceAction */
        GuidanceAction: {
            /** Action Code */
            action_code: string;
            /**
             * Jurisdiction Ids
             * @default []
             */
            jurisdiction_ids: string[];
            /**
             * Topic Refs
             * @default []
             */
            topic_refs: string[];
            /**
             * Evidence Refs
             * @default []
             */
            evidence_refs: string[];
        };
        /** KnowledgeRuntimeReadinessResult */
        KnowledgeRuntimeReadinessResult: {
            /** Knowledge Version Id */
            knowledge_version_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Publication Event Id */
            publication_event_id: string;
            /** Event Version */
            event_version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING" | "BUILDING" | "READY" | "FAILED";
            /** Index Version Id */
            index_version_id?: string | null;
            /** Embedding Config Id */
            embedding_config_id?: string | null;
            /** Registry Projection Version */
            registry_projection_version?: string | null;
            /** Cache Generation */
            cache_generation?: string | null;
            /** Checks */
            checks?: {
                [key: string]: boolean;
            };
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /** Assets */
            assets?: {
                [key: string]: unknown;
            };
            /** Record Version */
            record_version: number;
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    jurisdictions_api_v1_metadata_jurisdictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    scenarios_api_v1_metadata_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    products_api_v1_metadata_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    project_scope_api_v1_projects__project_id__knowledge_scope_get: {
        parameters: {
            query?: {
                analysis_snapshot_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeScope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_api_v1_projects__project_id__knowledge_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrievalRequestDTO"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieval_run_api_v1_retrieval_runs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResponseDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_pack_api_v1_evidence_packs__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sufficiency_api_v1_knowledge_sufficiency__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSufficiencyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runtime_readiness_api_v1_admin_knowledge_versions__id__runtime_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRuntimeReadinessResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
