/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClassificationResult */
        ClassificationResult: {
            /**
             * Classification Result Id
             * Format: uuid
             */
            classification_result_id?: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Data Item Id
             * Format: uuid
             */
            data_item_id: string;
            /**
             * Jurisdiction Id
             * Format: uuid
             */
            jurisdiction_id: string;
            /**
             * Scheme Id
             * Format: uuid
             */
            scheme_id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            /** Category Ids */
            category_ids: string[];
            /** Level Id */
            level_id: string | null;
            /** Rule Hit Ids */
            rule_hit_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Evidence Pack Ids
             * @default []
             */
            evidence_pack_ids: string[];
            /** Source Fact Refs */
            source_fact_refs: string[];
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: number;
            /** Review Required */
            review_required: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "CLASSIFIED" | "REVIEW_REQUIRED";
            /**
             * Record Version
             * @default 1
             */
            record_version: number;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Generated By
             * @default SAFE_RULE_ENGINE_V1
             * @constant
             */
            generated_by: "SAFE_RULE_ENGINE_V1";
        };
        /** ActionableFallbackGuidanceContext */
        ActionableFallbackGuidanceContext: {
            /**
             * Verified Requirements
             * @default []
             */
            verified_requirements: string[];
            /**
             * Verified Controls
             * @default []
             */
            verified_controls: string[];
            /** Conservative Controls */
            conservative_controls: components["schemas"]["GuidanceAction"][];
            /** Evidence Acquisition Steps */
            evidence_acquisition_steps: components["schemas"]["GuidanceAction"][];
            /** Jurisdiction Verification Steps */
            jurisdiction_verification_steps: components["schemas"]["GuidanceAction"][];
            /** Unresolved Legal Questions */
            unresolved_legal_questions: string[];
            /** Operational Next Steps */
            operational_next_steps: components["schemas"]["GuidanceAction"][];
            /** Prohibited Assertions */
            prohibited_assertions: string[];
            /**
             * Evidence Status
             * @enum {string}
             */
            evidence_status: "SUFFICIENT" | "PARTIALLY_SUFFICIENT" | "INSUFFICIENT" | "CONFLICTED";
            /** Confidence */
            confidence: number;
            /**
             * Review Recommended
             * @default true
             */
            review_recommended: boolean;
            /**
             * Finalization Requires Verification
             * @default true
             * @constant
             */
            finalization_requires_verification: true;
            /**
             * Compliance Path
             * @default false
             * @constant
             */
            compliance_path: false;
        };
        /** GuidanceAction */
        GuidanceAction: {
            /** Action Code */
            action_code: string;
            /**
             * Jurisdiction Ids
             * @default []
             */
            jurisdiction_ids: string[];
            /**
             * Topic Refs
             * @default []
             */
            topic_refs: string[];
            /**
             * Evidence Refs
             * @default []
             */
            evidence_refs: string[];
        };
        /** RegulationApplicabilityResult */
        RegulationApplicabilityResult: {
            /**
             * Applicability Result Id
             * Format: uuid
             */
            applicability_result_id?: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Data Item Ids */
            data_item_ids: string[];
            /** Data Flow Ids */
            data_flow_ids: string[];
            /** Scenario Definition Ids */
            scenario_definition_ids: string[];
            /**
             * Jurisdiction Id
             * Format: uuid
             */
            jurisdiction_id: string;
            /**
             * Regulation Document Id
             * Format: uuid
             */
            regulation_document_id: string;
            /**
             * Regulation Version Ref
             * Format: uuid
             */
            regulation_version_ref: string;
            /** Regulatory Structure Node Ids */
            regulatory_structure_node_ids: string[];
            /**
             * Applicability Status
             * @enum {string}
             */
            applicability_status: "APPLICABLE" | "NOT_APPLICABLE" | "CONDITIONALLY_APPLICABLE" | "INSUFFICIENT_EVIDENCE" | "CONFLICTED" | "REVIEW_REQUIRED";
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /** Classification Result Ids */
            classification_result_ids: string[];
            /** Rule Hit Ids */
            rule_hit_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Evidence Pack Ids */
            evidence_pack_ids: string[];
            /** Legal Basis Ids */
            legal_basis_ids: string[];
            /** Country Profile Id */
            country_profile_id: string | null;
            /** Country Profile Version Id */
            country_profile_version_id: string | null;
            /** Country Profile Version */
            country_profile_version: number | null;
            /** Scenario Adjustment Profile Versions */
            scenario_adjustment_profile_versions: [
                string,
                string,
                number
            ][];
            /**
             * Applicability Config Id
             * Format: uuid
             */
            applicability_config_id: string;
            /**
             * Applicability Config Version Id
             * Format: uuid
             */
            applicability_config_version_id: string;
            /** Applicability Config Version */
            applicability_config_version: number;
            /** Confidence */
            confidence: number;
            /** Review Required */
            review_required: boolean;
            /**
             * Conflict Status
             * @enum {string}
             */
            conflict_status: "CLEAR" | "CONFLICTED";
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Context Version */
            context_version: number;
            /**
             * Record Version
             * @default 1
             */
            record_version: number;
            /**
             * Generated By
             * @default RULE_EVIDENCE_APPLICABILITY_V1
             * @constant
             */
            generated_by: "RULE_EVIDENCE_APPLICABILITY_V1";
            /** @default null */
            fallback_guidance_context: components["schemas"]["ActionableFallbackGuidanceContext"] | null;
            /**
             * Legal Obligation
             * @default false
             * @constant
             */
            legal_obligation: false;
        };
        /** ProvenanceDTO */
        ProvenanceDTO: {
            /** Source Type */
            source_type: string;
            /** Source Ref */
            source_ref: string;
            /**
             * Source Version
             * @default null
             */
            source_version: string | null;
            /**
             * Source Locator
             * @default null
             */
            source_locator: string | null;
            /**
             * Actor Ref
             * @default null
             */
            actor_ref: string | null;
            /**
             * Request Id
             * @default null
             */
            request_id: string | null;
            /**
             * Correlation Id
             * @default null
             */
            correlation_id: string | null;
            /** Generated By */
            generated_by: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** ProjectIntakeContext */
        ProjectIntakeContext: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /**
             * Record Version
             * @default 1
             */
            record_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * @default null
             */
            updated_at: string | null;
            provenance: components["schemas"]["ProvenanceDTO"];
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Project Name */
            project_name: string;
            /**
             * Industry
             * @default null
             */
            industry: string | null;
            /**
             * Business Scenario
             * @default null
             */
            business_scenario: string | null;
            /**
             * Scenario Description
             * @default null
             */
            scenario_description: string | null;
            /** Selected Product Domains */
            selected_product_domains?: string[];
            /** Selected Products */
            selected_products?: string[];
            /** Source Locations */
            source_locations?: string[];
            /** Destination Locations */
            destination_locations?: string[];
            /** Processing Locations */
            processing_locations?: string[];
            /** Storage Locations */
            storage_locations?: string[];
            /**
             * Data Flow Description
             * @default null
             */
            data_flow_description: string | null;
            /** Data Categories */
            data_categories?: string[];
            /**
             * Data Volume
             * @default null
             */
            data_volume: string | null;
            /**
             * Business Purpose
             * @default null
             */
            business_purpose: string | null;
            /** Organizations */
            organizations?: string[];
            /** Third Parties */
            third_parties?: string[];
            /** Uploaded Documents */
            uploaded_documents?: string[];
            /** Requested Outputs */
            requested_outputs?: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
