/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workflows/{run_id}/stage1-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stage1 Result */
        get: operations["stage1_result_api_v1_workflows__run_id__stage1_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Action */
        Action: {
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /** Action Code */
            action_code: string;
            /** Sequence */
            sequence: number;
            /**
             * Responsible Party Ids
             * @default []
             */
            responsible_party_ids: string[];
            /**
             * Conditions
             * @default []
             */
            conditions: components["schemas"]["Condition"][];
            /**
             * Dependency Entry Ids
             * @default []
             */
            dependency_entry_ids: string[];
            /**
             * Obligation Ids
             * @default []
             */
            obligation_ids: string[];
            /**
             * Performed
             * @default false
             * @constant
             */
            performed: false;
        };
        /** ActionableFallbackGuidanceContext */
        ActionableFallbackGuidanceContext: {
            /**
             * Verified Requirements
             * @default []
             */
            verified_requirements: string[];
            /**
             * Verified Controls
             * @default []
             */
            verified_controls: string[];
            /** Conservative Controls */
            conservative_controls: components["schemas"]["GuidanceAction"][];
            /** Evidence Acquisition Steps */
            evidence_acquisition_steps: components["schemas"]["GuidanceAction"][];
            /** Jurisdiction Verification Steps */
            jurisdiction_verification_steps: components["schemas"]["GuidanceAction"][];
            /** Unresolved Legal Questions */
            unresolved_legal_questions: string[];
            /** Operational Next Steps */
            operational_next_steps: components["schemas"]["GuidanceAction"][];
            /** Prohibited Assertions */
            prohibited_assertions: string[];
            /**
             * Evidence Status
             * @enum {string}
             */
            evidence_status: "SUFFICIENT" | "PARTIALLY_SUFFICIENT" | "INSUFFICIENT" | "CONFLICTED";
            /** Confidence */
            confidence: number;
            /**
             * Review Recommended
             * @default true
             */
            review_recommended: boolean;
            /**
             * Finalization Requires Verification
             * @default true
             * @constant
             */
            finalization_requires_verification: true;
            /**
             * Compliance Path
             * @default false
             * @constant
             */
            compliance_path: false;
        };
        /** AuthorityProvenance */
        AuthorityProvenance: {
            /** Origins */
            origins: components["schemas"]["AuthorityRef"][];
            /** Context Fact Refs */
            context_fact_refs: string[];
            /** Retrieval Run Ids */
            retrieval_run_ids: string[];
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /**
             * Engine Version
             * @default FORMAL_RESULT_AUTHORITY_V2
             * @constant
             */
            engine_version: "FORMAL_RESULT_AUTHORITY_V2";
            /**
             * Schema Version
             * @default 2.0
             * @constant
             */
            schema_version: "2.0";
            /**
             * Computation Timestamp
             * Format: date-time
             */
            computation_timestamp: string;
            /** Actor Ref */
            actor_ref: string;
            /** Request Id */
            request_id: string;
            /** Correlation Id */
            correlation_id: string;
        };
        /** AuthorityRef */
        AuthorityRef: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "APPLICABILITY" | "OBLIGATION" | "CANDIDATE_PATH" | "RISK" | "RECOMMENDATION" | "FINAL_PATH" | "CROSS_BORDER" | "DOCUMENT_REQUIREMENT";
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /** Item Id */
            item_id?: string | null;
            /** Content Digest */
            content_digest: string;
        };
        /** CandidateCompliancePathDTOv2 */
        CandidateCompliancePathDTOv2: {
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            support: components["schemas"]["LegalSupport"];
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Review Required
             * @default false
             */
            review_required: boolean;
            /**
             * Policy Version Ref
             * Format: uuid
             */
            policy_version_ref: string;
            /**
             * Candidate Path Id
             * Format: uuid
             */
            candidate_path_id: string;
            /** Path Code */
            path_code: string;
            /**
             * Template Entry Id
             * Format: uuid
             */
            template_entry_id: string;
            /** Obligation Ids */
            obligation_ids: string[];
            /** Prerequisites */
            prerequisites: components["schemas"]["Condition"][];
            /** Unmet Requirement Ids */
            unmet_requirement_ids: string[];
            /** Mechanism Entry Ids */
            mechanism_entry_ids: string[];
            /** Capability Dependencies */
            capability_dependencies: components["schemas"]["CapabilityDependency"][];
            /**
             * Legal Viability
             * @enum {string}
             */
            legal_viability: "VIABLE" | "CONDITIONAL" | "LEGALLY_PROHIBITED" | "UNDETERMINED";
            /**
             * Operational Availability
             * @enum {string}
             */
            operational_availability: "AVAILABLE" | "CAPABILITY_NOT_CONFIGURED" | "UNAVAILABLE" | "UNKNOWN";
            /** Steps */
            steps: components["schemas"]["Action"][];
            /** Template Priority */
            template_priority: number;
        };
        /** CapabilityDependency */
        CapabilityDependency: {
            /**
             * Capability Id
             * Format: uuid
             */
            capability_id: string;
            /** Version Id */
            version_id: string | null;
            /**
             * Availability
             * @enum {string}
             */
            availability: "AVAILABLE" | "CAPABILITY_NOT_CONFIGURED" | "UNAVAILABLE" | "UNKNOWN";
        };
        /** ClassificationResult */
        ClassificationResult: {
            /**
             * Classification Result Id
             * Format: uuid
             */
            classification_result_id?: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Data Item Id
             * Format: uuid
             */
            data_item_id: string;
            /**
             * Jurisdiction Id
             * Format: uuid
             */
            jurisdiction_id: string;
            /**
             * Scheme Id
             * Format: uuid
             */
            scheme_id: string;
            /**
             * Scheme Version Id
             * Format: uuid
             */
            scheme_version_id: string;
            /** Category Ids */
            category_ids: string[];
            /** Level Id */
            level_id: string | null;
            /** Rule Hit Ids */
            rule_hit_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /**
             * Evidence Pack Ids
             * @default []
             */
            evidence_pack_ids: string[];
            /** Source Fact Refs */
            source_fact_refs: string[];
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: number;
            /** Review Required */
            review_required: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "CLASSIFIED" | "REVIEW_REQUIRED";
            /**
             * Record Version
             * @default 1
             */
            record_version: number;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Generated By
             * @default SAFE_RULE_ENGINE_V1
             * @constant
             */
            generated_by: "SAFE_RULE_ENGINE_V1";
        };
        /** ComplianceObligationDTOv2 */
        ComplianceObligationDTOv2: {
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            support: components["schemas"]["LegalSupport"];
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Review Required
             * @default false
             */
            review_required: boolean;
            /**
             * Policy Version Ref
             * Format: uuid
             */
            policy_version_ref: string;
            /**
             * Obligation Id
             * Format: uuid
             */
            obligation_id: string;
            /**
             * Requirement Id
             * Format: uuid
             */
            requirement_id: string;
            /** Obligation Code */
            obligation_code: string;
            /**
             * Legal Effect
             * @enum {string}
             */
            legal_effect: "REQUIRED" | "CONDITIONAL" | "NOT_APPLICABLE" | "UNDETERMINED";
            /**
             * Fulfillment State
             * @enum {string}
             */
            fulfillment_state: "SATISFIED" | "UNMET" | "UNKNOWN" | "NOT_APPLICABLE";
            /** Conditions */
            conditions: components["schemas"]["Condition"][];
            /**
             * Responsible Party Ids
             * @default []
             */
            responsible_party_ids: string[];
            /**
             * Legal Effect Code
             * @enum {string}
             */
            legal_effect_code: "REQUIREMENT" | "TRANSFER_PROHIBITED" | "LOCALIZATION_REQUIRED";
        };
        /** ComplianceRecommendationDTOv2 */
        ComplianceRecommendationDTOv2: {
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            support: components["schemas"]["LegalSupport"];
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Review Required
             * @default false
             */
            review_required: boolean;
            /**
             * Policy Version Ref
             * Format: uuid
             */
            policy_version_ref: string;
            /**
             * Recommendation Id
             * Format: uuid
             */
            recommendation_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "RECOMMENDED" | "CONDITIONAL_ALTERNATIVES" | "TIED" | "NO_RECOMMENDATION" | "NOT_APPLICABLE";
            /** Selected Candidate Id */
            selected_candidate_id: string | null;
            /** Rankings */
            rankings: components["schemas"]["RankingOutcome"][];
            /** Excluded Candidates */
            excluded_candidates: components["schemas"]["ExcludedCandidate"][];
            /** Alternative Candidate Ids */
            alternative_candidate_ids: string[];
            /** Tied Candidate Ids */
            tied_candidate_ids: string[];
            /** Risk Assessment Ids */
            risk_assessment_ids: string[];
        };
        /** Condition */
        Condition: {
            /**
             * Entry Id
             * Format: uuid
             */
            entry_id: string;
            /** Code */
            code: string;
            /** Predicate Digest */
            predicate_digest: string;
            /**
             * Evaluation
             * @enum {string}
             */
            evaluation: "TRUE" | "FALSE" | "UNKNOWN";
            /**
             * Fact Refs
             * @default []
             */
            fact_refs: string[];
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
        };
        /** CrossBorderAssessmentDTOv2 */
        CrossBorderAssessmentDTOv2: {
            /**
             * Cross Border Assessment Id
             * Format: uuid
             */
            cross_border_assessment_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Data Item Ids */
            data_item_ids: string[];
            /** Data Flow Ids */
            data_flow_ids: string[];
            /** Source Jurisdiction Ids */
            source_jurisdiction_ids: string[];
            /** Destination Jurisdiction Ids */
            destination_jurisdiction_ids: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "DIRECT_TRANSFER_ALLOWED" | "CONDITIONAL_TRANSFER_ALLOWED" | "TRANSFER_NOT_ALLOWED_OR_LOCALIZATION_REQUIRED" | "REVIEW_REQUIRED" | "NOT_APPLICABLE";
            /** Reason Codes */
            reason_codes: string[];
            /** Localization Required */
            localization_required: boolean;
            /** Filing Required */
            filing_required: boolean;
            /** Assessment Required */
            assessment_required: boolean;
            /** Approval Required */
            approval_required: boolean;
            /** Obligation Ids */
            obligation_ids: string[];
            /** Applicability Result Ids */
            applicability_result_ids: string[];
            /** Rule Hit Ids */
            rule_hit_ids: string[];
            /** Legal Basis Ids */
            legal_basis_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Policy Version Id */
            policy_version_id: string | null;
            /** Review Required */
            review_required: boolean;
            /** Confidence */
            confidence: string;
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
        };
        /** CrossBorderAssessmentResult */
        CrossBorderAssessmentResult: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Data Item Ids
             * @default []
             */
            data_item_ids: string[];
            /**
             * Data Flow Ids
             * @default []
             */
            data_flow_ids: string[];
            /**
             * Scenario Definition Ids
             * @default []
             */
            scenario_definition_ids: string[];
            /**
             * Jurisdiction Ids
             * @default []
             */
            jurisdiction_ids: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /**
             * Stage Kind
             * @default CROSS_BORDER
             * @constant
             */
            stage_kind: "CROSS_BORDER";
            /** Upstream Refs */
            upstream_refs: components["schemas"]["AuthorityRef"][];
            /** Items */
            items: components["schemas"]["CrossBorderAssessmentDTOv2"][];
            /**
             * Input Sufficiency
             * @enum {string}
             */
            input_sufficiency: "SUFFICIENT" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN";
            /**
             * Conflict State
             * @enum {string}
             */
            conflict_state: "CLEAR" | "CONFLICTED";
            /** Review Required */
            review_required: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: string;
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
            /**
             * Engine Version
             * @default FORMAL_RESULT_AUTHORITY_V2
             * @constant
             */
            engine_version: "FORMAL_RESULT_AUTHORITY_V2";
            provenance: components["schemas"]["AuthorityProvenance"];
            /** Ordinary Status */
            ordinary_status: string;
        };
        /** DataItemSummary */
        DataItemSummary: {
            /**
             * Data Item Id
             * Format: uuid
             */
            data_item_id: string;
            /** Name */
            name: string;
            /** Validation Status */
            validation_status: string;
            /** Review Required */
            review_required: boolean;
            /**
             * Source Trace Ids
             * @default []
             */
            source_trace_ids: string[];
        };
        /** DecisionEnvelope[CandidateCompliancePathDTOv2] */
        DecisionEnvelope_CandidateCompliancePathDTOv2_: {
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /**
             * Stage Kind
             * @enum {string}
             */
            stage_kind: "OBLIGATION" | "CANDIDATE_PATH" | "RISK" | "RECOMMENDATION" | "FINAL_PATH";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Data Item Ids
             * @default []
             */
            data_item_ids: string[];
            /**
             * Data Flow Ids
             * @default []
             */
            data_flow_ids: string[];
            /**
             * Scenario Definition Ids
             * @default []
             */
            scenario_definition_ids: string[];
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /** Upstream Refs */
            upstream_refs: components["schemas"]["StageRef"][];
            /** Items */
            items: components["schemas"]["CandidateCompliancePathDTOv2"][];
            /**
             * Input Sufficiency
             * @enum {string}
             */
            input_sufficiency: "SUFFICIENT" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN";
            /**
             * Conflict State
             * @enum {string}
             */
            conflict_state: "CLEAR" | "CONFLICTED";
            /** Review Required */
            review_required: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: string;
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
            /**
             * Engine Version
             * @default FORMAL_DECISION_V2
             * @constant
             */
            engine_version: "FORMAL_DECISION_V2";
            provenance: components["schemas"]["DecisionProvenance"];
            /** Ordinary Status */
            ordinary_status: string;
        };
        /** DecisionEnvelope[ComplianceObligationDTOv2] */
        DecisionEnvelope_ComplianceObligationDTOv2_: {
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /**
             * Stage Kind
             * @enum {string}
             */
            stage_kind: "OBLIGATION" | "CANDIDATE_PATH" | "RISK" | "RECOMMENDATION" | "FINAL_PATH";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Data Item Ids
             * @default []
             */
            data_item_ids: string[];
            /**
             * Data Flow Ids
             * @default []
             */
            data_flow_ids: string[];
            /**
             * Scenario Definition Ids
             * @default []
             */
            scenario_definition_ids: string[];
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /** Upstream Refs */
            upstream_refs: components["schemas"]["StageRef"][];
            /** Items */
            items: components["schemas"]["ComplianceObligationDTOv2"][];
            /**
             * Input Sufficiency
             * @enum {string}
             */
            input_sufficiency: "SUFFICIENT" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN";
            /**
             * Conflict State
             * @enum {string}
             */
            conflict_state: "CLEAR" | "CONFLICTED";
            /** Review Required */
            review_required: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: string;
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
            /**
             * Engine Version
             * @default FORMAL_DECISION_V2
             * @constant
             */
            engine_version: "FORMAL_DECISION_V2";
            provenance: components["schemas"]["DecisionProvenance"];
            /** Ordinary Status */
            ordinary_status: string;
        };
        /** DecisionEnvelope[ComplianceRecommendationDTOv2] */
        DecisionEnvelope_ComplianceRecommendationDTOv2_: {
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /**
             * Stage Kind
             * @enum {string}
             */
            stage_kind: "OBLIGATION" | "CANDIDATE_PATH" | "RISK" | "RECOMMENDATION" | "FINAL_PATH";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Data Item Ids
             * @default []
             */
            data_item_ids: string[];
            /**
             * Data Flow Ids
             * @default []
             */
            data_flow_ids: string[];
            /**
             * Scenario Definition Ids
             * @default []
             */
            scenario_definition_ids: string[];
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /** Upstream Refs */
            upstream_refs: components["schemas"]["StageRef"][];
            /** Items */
            items: components["schemas"]["ComplianceRecommendationDTOv2"][];
            /**
             * Input Sufficiency
             * @enum {string}
             */
            input_sufficiency: "SUFFICIENT" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN";
            /**
             * Conflict State
             * @enum {string}
             */
            conflict_state: "CLEAR" | "CONFLICTED";
            /** Review Required */
            review_required: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: string;
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
            /**
             * Engine Version
             * @default FORMAL_DECISION_V2
             * @constant
             */
            engine_version: "FORMAL_DECISION_V2";
            provenance: components["schemas"]["DecisionProvenance"];
            /** Ordinary Status */
            ordinary_status: string;
        };
        /** DecisionEnvelope[FinalCompliancePathDTOv2] */
        DecisionEnvelope_FinalCompliancePathDTOv2_: {
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /**
             * Stage Kind
             * @enum {string}
             */
            stage_kind: "OBLIGATION" | "CANDIDATE_PATH" | "RISK" | "RECOMMENDATION" | "FINAL_PATH";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Data Item Ids
             * @default []
             */
            data_item_ids: string[];
            /**
             * Data Flow Ids
             * @default []
             */
            data_flow_ids: string[];
            /**
             * Scenario Definition Ids
             * @default []
             */
            scenario_definition_ids: string[];
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /** Upstream Refs */
            upstream_refs: components["schemas"]["StageRef"][];
            /** Items */
            items: components["schemas"]["FinalCompliancePathDTOv2"][];
            /**
             * Input Sufficiency
             * @enum {string}
             */
            input_sufficiency: "SUFFICIENT" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN";
            /**
             * Conflict State
             * @enum {string}
             */
            conflict_state: "CLEAR" | "CONFLICTED";
            /** Review Required */
            review_required: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: string;
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
            /**
             * Engine Version
             * @default FORMAL_DECISION_V2
             * @constant
             */
            engine_version: "FORMAL_DECISION_V2";
            provenance: components["schemas"]["DecisionProvenance"];
            /** Ordinary Status */
            ordinary_status: string;
        };
        /** DecisionEnvelope[RiskAssessmentDTOv2] */
        DecisionEnvelope_RiskAssessmentDTOv2_: {
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /**
             * Stage Kind
             * @enum {string}
             */
            stage_kind: "OBLIGATION" | "CANDIDATE_PATH" | "RISK" | "RECOMMENDATION" | "FINAL_PATH";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Data Item Ids
             * @default []
             */
            data_item_ids: string[];
            /**
             * Data Flow Ids
             * @default []
             */
            data_flow_ids: string[];
            /**
             * Scenario Definition Ids
             * @default []
             */
            scenario_definition_ids: string[];
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /** Upstream Refs */
            upstream_refs: components["schemas"]["StageRef"][];
            /** Items */
            items: components["schemas"]["RiskAssessmentDTOv2"][];
            /**
             * Input Sufficiency
             * @enum {string}
             */
            input_sufficiency: "SUFFICIENT" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN";
            /**
             * Conflict State
             * @enum {string}
             */
            conflict_state: "CLEAR" | "CONFLICTED";
            /** Review Required */
            review_required: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: string;
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
            /**
             * Engine Version
             * @default FORMAL_DECISION_V2
             * @constant
             */
            engine_version: "FORMAL_DECISION_V2";
            provenance: components["schemas"]["DecisionProvenance"];
            /** Ordinary Status */
            ordinary_status: string;
        };
        /** DecisionProvenance */
        DecisionProvenance: {
            /** Origins */
            origins: components["schemas"]["StageRef"][];
            /** Context Fact Refs */
            context_fact_refs: string[];
            /** Retrieval Run Ids */
            retrieval_run_ids: string[];
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /**
             * Engine Version
             * @default FORMAL_DECISION_V2
             * @constant
             */
            engine_version: "FORMAL_DECISION_V2";
            /**
             * Schema Version
             * @default 2.0
             * @constant
             */
            schema_version: "2.0";
            /**
             * Computation Timestamp
             * Format: date-time
             */
            computation_timestamp: string;
            /** Actor Ref */
            actor_ref: string;
            /** Request Id */
            request_id: string;
            /** Correlation Id */
            correlation_id: string;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /**
             * Parse Run Id
             * Format: uuid
             */
            parse_run_id: string;
            /** Name */
            name: string;
            /** Version */
            version: number;
            /** Parse Status */
            parse_status: string;
            /** Parser Version */
            parser_version: string;
        };
        /** EvidencePack */
        EvidencePack: {
            /** Evidence Pack Id */
            evidence_pack_id: string;
            /** Retrieval Run Id */
            retrieval_run_id: string;
            /** Analysis Snapshot Id */
            analysis_snapshot_id: string;
            /** Items */
            items: components["schemas"]["EvidencePackItem"][];
            /** Manifest */
            manifest: {
                [key: string]: unknown;
            };
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
            /**
             * Legal Source Of Truth
             * @default false
             * @constant
             */
            legal_source_of_truth: false;
        };
        /** EvidencePackItem */
        EvidencePackItem: {
            /** Evidence Item Id */
            evidence_item_id: string;
            /** Knowledge Document Id */
            knowledge_document_id?: string | null;
            /** Knowledge Version Id */
            knowledge_version_id?: string | null;
            /** External Evidence Id */
            external_evidence_id?: string | null;
            /** Structure Node Id */
            structure_node_id: string;
            /** Chunk Id */
            chunk_id: string;
            /** Citation Id */
            citation_id: string;
            /** Source Id */
            source_id: string;
            /** Source Url */
            source_url: string;
            /** Source Authority */
            source_authority?: string | null;
            /**
             * Source Tier
             * @enum {string}
             */
            source_tier: "T1_PRIMARY_OFFICIAL" | "T2_OFFICIAL_GUIDANCE" | "T3_INTERGOVERNMENTAL" | "T3_APPROVED_SECONDARY" | "T4_UNVERIFIED_WEB" | "T4_LLM_DISCOVERY_ONLY";
            /** Jurisdiction Id */
            jurisdiction_id?: string | null;
            /**
             * Jurisdiction Specific
             * @default false
             */
            jurisdiction_specific: boolean;
            /** Canonical Locator */
            canonical_locator: string;
            /** Language */
            language: string;
            /** Effective From */
            effective_from?: string | null;
            /** Effective To */
            effective_to?: string | null;
            /** Lexical Score */
            lexical_score?: number | null;
            /** Vector Score */
            vector_score?: number | null;
            /**
             * Hybrid Score
             * @default 0
             */
            hybrid_score: number;
            /** Rerank Score */
            rerank_score?: number | null;
            /**
             * Scope Validation Status
             * @default VALIDATED
             * @constant
             */
            scope_validation_status: "VALIDATED";
            /** Evidence Quality */
            evidence_quality: number;
            /** Content Hash */
            content_hash: string;
            /** Retrieval Run Id */
            retrieval_run_id: string;
            /** Analysis Snapshot Id */
            analysis_snapshot_id: string;
            /** Knowledge Index Version */
            knowledge_index_version?: string | null;
            /** Retrieval Policy Version */
            retrieval_policy_version: string;
            /** Original Text */
            original_text: string;
            /**
             * Topic Refs
             * @default []
             */
            topic_refs: string[];
            /**
             * Regulation Refs
             * @default []
             */
            regulation_refs: string[];
            /** Conflict Key */
            conflict_key?: string | null;
            /** Claim Hash */
            claim_hash?: string | null;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
            /**
             * Legal Decision
             * @default false
             * @constant
             */
            legal_decision: false;
        };
        /** ExcludedCandidate */
        ExcludedCandidate: {
            /**
             * Candidate Path Id
             * Format: uuid
             */
            candidate_path_id: string;
            /** Reason Codes */
            reason_codes: string[];
        };
        /** FinalCompliancePathDTOv2 */
        FinalCompliancePathDTOv2: {
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            support: components["schemas"]["LegalSupport"];
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Review Required
             * @default false
             */
            review_required: boolean;
            /**
             * Policy Version Ref
             * Format: uuid
             */
            policy_version_ref: string;
            /**
             * Final Path Id
             * Format: uuid
             */
            final_path_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PROPOSED" | "CONDITIONAL_PROPOSAL" | "NO_VIABLE_PATH" | "NOT_APPLICABLE" | "UNDETERMINED" | "LEGALLY_PROHIBITED";
            /** Selected Candidate Path Id */
            selected_candidate_path_id: string | null;
            /** Obligation Ids */
            obligation_ids: string[];
            /** Required Conditions */
            required_conditions: components["schemas"]["Condition"][];
            /** Actions */
            actions: components["schemas"]["Action"][];
            /** Unmet Requirement Ids */
            unmet_requirement_ids: string[];
            residual_risk_ref: components["schemas"]["StageRef"] | null;
            /** Alternative Candidate Ids */
            alternative_candidate_ids: string[];
            /** Unresolved Codes */
            unresolved_codes: string[];
            /**
             * Review Status
             * @enum {string}
             */
            review_status: "NOT_REQUIRED" | "PENDING";
        };
        /** FlowNodeSummary */
        FlowNodeSummary: {
            /**
             * Flow Node Id
             * Format: uuid
             */
            flow_node_id: string;
            /** Name */
            name: string;
            /** Jurisdiction Id */
            jurisdiction_id: string | null;
        };
        /** FlowSummary */
        FlowSummary: {
            /**
             * Flow Edge Id
             * Format: uuid
             */
            flow_edge_id: string;
            /**
             * Source Node Id
             * Format: uuid
             */
            source_node_id: string;
            /**
             * Target Node Id
             * Format: uuid
             */
            target_node_id: string;
            /** Data Item Ids */
            data_item_ids: string[];
            /** Validation Status */
            validation_status: string;
        };
        /** FormalContext */
        FormalContext: {
            /** Project Id */
            project_id: string;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "PROJECT" | "DATA_ITEM" | "DATA_FLOW";
            /** Subject Id */
            subject_id: string;
            /** Context Version */
            context_version: number;
            /** Dimensions */
            dimensions: {
                [key: string]: string[];
            };
            /** Product Unresolved */
            product_unresolved: boolean;
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /**
             * System Ids
             * @default []
             */
            system_ids: string[];
            /**
             * Party Ids
             * @default []
             */
            party_ids: string[];
            /**
             * Product Lineages
             * @default {}
             */
            product_lineages: {
                [key: string]: {
                    [key: string]: string[];
                };
            };
        };
        /** GuidanceAction */
        GuidanceAction: {
            /** Action Code */
            action_code: string;
            /**
             * Jurisdiction Ids
             * @default []
             */
            jurisdiction_ids: string[];
            /**
             * Topic Refs
             * @default []
             */
            topic_refs: string[];
            /**
             * Evidence Refs
             * @default []
             */
            evidence_refs: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** KnowledgeFilterSpec */
        KnowledgeFilterSpec: {
            /** Tenant Filter */
            tenant_filter: string;
            /** Permission Filter */
            permission_filter: string[];
            /** Lifecycle Filter */
            lifecycle_filter: string[];
            /**
             * Effective Date Filter
             * Format: date
             */
            effective_date_filter: string;
            /** Jurisdiction Filter */
            jurisdiction_filter: string[];
            /** Product Filter */
            product_filter: {
                [key: string]: string[];
            };
            /** Scenario Filter */
            scenario_filter: string[];
            /** Industry Filter */
            industry_filter: string[];
            /** Data Category Filter */
            data_category_filter: string[];
            /** Language Filter */
            language_filter: string[];
            /** Scope Type Filter */
            scope_type_filter: string[];
            /** Version Filter */
            version_filter: string[];
            /** Binding Filter */
            binding_filter: string[];
            /**
             * Filter Order
             * @default [
             *       "tenant",
             *       "permission",
             *       "lifecycle",
             *       "version",
             *       "effective_date",
             *       "product",
             *       "jurisdiction",
             *       "scenario",
             *       "industry",
             *       "data_category",
             *       "language"
             *     ]
             */
            filter_order: string[];
        };
        /** KnowledgeScope */
        KnowledgeScope: {
            /** Tenant Id */
            tenant_id: string;
            /** Project Id */
            project_id: string;
            /** Analysis Snapshot Id */
            analysis_snapshot_id?: string | null;
            /** Subject Type */
            subject_type: string;
            /** Subject Id */
            subject_id: string;
            /**
             * Allowed Jurisdiction Ids
             * @default []
             */
            allowed_jurisdiction_ids: string[];
            /**
             * Allowed Product Domain Ids
             * @default []
             */
            allowed_product_domain_ids: string[];
            /**
             * Allowed Product Category Ids
             * @default []
             */
            allowed_product_category_ids: string[];
            /**
             * Allowed Product Family Ids
             * @default []
             */
            allowed_product_family_ids: string[];
            /**
             * Allowed Product Ids
             * @default []
             */
            allowed_product_ids: string[];
            /**
             * Allowed Product Tag Ids
             * @default []
             */
            allowed_product_tag_ids: string[];
            /**
             * Allowed Scenario Ids
             * @default []
             */
            allowed_scenario_ids: string[];
            /**
             * Allowed Industry Refs
             * @default []
             */
            allowed_industry_refs: string[];
            /**
             * Allowed Data Category Refs
             * @default []
             */
            allowed_data_category_refs: string[];
            /** Allowed Scope Types */
            allowed_scope_types: string[];
            /** Permission Filters */
            permission_filters: string[];
            /** Lifecycle Filters */
            lifecycle_filters: string[];
            /**
             * Effective As Of
             * Format: date
             */
            effective_as_of: string;
            /** Excluded Bindings */
            excluded_bindings: {
                [key: string]: unknown;
            }[];
            /** Unresolved Scopes */
            unresolved_scopes: string[];
            /** Reason Codes */
            reason_codes: string[];
            /** Review Required */
            review_required: boolean;
            /** Version */
            version: number;
            filter_spec: components["schemas"]["KnowledgeFilterSpec"];
        };
        /** KnowledgeSufficiencyResult */
        KnowledgeSufficiencyResult: {
            /** Sufficiency Result Id */
            sufficiency_result_id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Project Id */
            project_id: string;
            /** Analysis Snapshot Id */
            analysis_snapshot_id: string;
            /** Subject Type */
            subject_type: string;
            /** Subject Id */
            subject_id: string;
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            /** Retrieval Run Id */
            retrieval_run_id: string;
            /** Evidence Pack Id */
            evidence_pack_id: string;
            /** Jurisdiction Coverage */
            jurisdiction_coverage: {
                [key: string]: boolean;
            };
            /** Regulation Coverage */
            regulation_coverage: {
                [key: string]: boolean;
            };
            /** Official Source Coverage */
            official_source_coverage: number;
            /** Effective Date Coverage */
            effective_date_coverage: number;
            /** Evidence Quality */
            evidence_quality: number;
            /** Evidence Count */
            evidence_count: number;
            /** Conflicting Evidence Count */
            conflicting_evidence_count: number;
            /** Missing Topics */
            missing_topics: string[];
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: number;
            /** Review Required */
            review_required: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "SUFFICIENT" | "PARTIALLY_SUFFICIENT" | "INSUFFICIENT" | "CONFLICTED";
            /** Policy Version */
            policy_version: string;
        };
        /** LegalSupport */
        LegalSupport: {
            /**
             * Applicability Result Ids
             * @default []
             */
            applicability_result_ids: string[];
            /**
             * Rule Hit Ids
             * @default []
             */
            rule_hit_ids: string[];
            /**
             * Rule Version Ids
             * @default []
             */
            rule_version_ids: string[];
            /**
             * Legal Basis Ids
             * @default []
             */
            legal_basis_ids: string[];
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
            /**
             * Evidence Pack Ids
             * @default []
             */
            evidence_pack_ids: string[];
            /**
             * Retrieval Run Ids
             * @default []
             */
            retrieval_run_ids: string[];
            /**
             * Knowledge Version Ids
             * @default []
             */
            knowledge_version_ids: string[];
            /**
             * Structure Node Ids
             * @default []
             */
            structure_node_ids: string[];
            /**
             * Citation Ids
             * @default []
             */
            citation_ids: string[];
            /**
             * Citation Locators
             * @default []
             */
            citation_locators: string[];
            /**
             * Fact Refs
             * @default []
             */
            fact_refs: string[];
        };
        /** OfficialLegalBasis */
        OfficialLegalBasis: {
            /**
             * Legal Basis Id
             * Format: uuid
             */
            legal_basis_id: string;
            /**
             * Jurisdiction Id
             * Format: uuid
             */
            jurisdiction_id: string;
            /** Summary */
            summary: string;
            /** Official Source */
            official_source: string;
            /** Citation Locator */
            citation_locator: string;
        };
        /** PinRef */
        PinRef: {
            /**
             * Pin Id
             * Format: uuid
             */
            pin_id: string;
            /** Kind */
            kind: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Version Id
             * Format: uuid
             */
            version_id: string;
            /** Version No */
            version_no: number;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Name */
            name: string;
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /**
             * Context Resolution Run Id
             * Format: uuid
             */
            context_resolution_run_id: string;
            /** Data Inventory Version */
            data_inventory_version: number;
            /** Formal Context Version */
            formal_context_version: number;
        };
        /** RAGContextPack */
        RAGContextPack: {
            structured_context: components["schemas"]["FormalContext"];
            scope: components["schemas"]["KnowledgeScope"];
            evidence_pack: components["schemas"]["EvidencePack"];
            knowledge_sufficiency: components["schemas"]["KnowledgeSufficiencyResult"];
            /** External Augmentation Metadata */
            external_augmentation_metadata: {
                [key: string]: unknown;
            };
            fallback_guidance_context?: components["schemas"]["ActionableFallbackGuidanceContext"] | null;
            /**
             * Derived
             * @default true
             * @constant
             */
            derived: true;
            /**
             * Legal Decision
             * @default false
             * @constant
             */
            legal_decision: false;
        };
        /** RankingOutcome */
        RankingOutcome: {
            /**
             * Candidate Path Id
             * Format: uuid
             */
            candidate_path_id: string;
            /** Criterion Values */
            criterion_values: string[];
        };
        /** RegulationApplicabilityResult */
        RegulationApplicabilityResult: {
            /**
             * Applicability Result Id
             * Format: uuid
             */
            applicability_result_id?: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Data Item Ids */
            data_item_ids: string[];
            /** Data Flow Ids */
            data_flow_ids: string[];
            /** Scenario Definition Ids */
            scenario_definition_ids: string[];
            /**
             * Jurisdiction Id
             * Format: uuid
             */
            jurisdiction_id: string;
            /**
             * Regulation Document Id
             * Format: uuid
             */
            regulation_document_id: string;
            /**
             * Regulation Version Ref
             * Format: uuid
             */
            regulation_version_ref: string;
            /** Regulatory Structure Node Ids */
            regulatory_structure_node_ids: string[];
            /**
             * Applicability Status
             * @enum {string}
             */
            applicability_status: "APPLICABLE" | "NOT_APPLICABLE" | "CONDITIONALLY_APPLICABLE" | "INSUFFICIENT_EVIDENCE" | "CONFLICTED" | "REVIEW_REQUIRED";
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /** Classification Result Ids */
            classification_result_ids: string[];
            /** Rule Hit Ids */
            rule_hit_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Evidence Pack Ids */
            evidence_pack_ids: string[];
            /** Legal Basis Ids */
            legal_basis_ids: string[];
            /** Country Profile Id */
            country_profile_id: string | null;
            /** Country Profile Version Id */
            country_profile_version_id: string | null;
            /** Country Profile Version */
            country_profile_version: number | null;
            /** Scenario Adjustment Profile Versions */
            scenario_adjustment_profile_versions: [
                string,
                string,
                number
            ][];
            /**
             * Applicability Config Id
             * Format: uuid
             */
            applicability_config_id: string;
            /**
             * Applicability Config Version Id
             * Format: uuid
             */
            applicability_config_version_id: string;
            /** Applicability Config Version */
            applicability_config_version: number;
            /** Confidence */
            confidence: number;
            /** Review Required */
            review_required: boolean;
            /**
             * Conflict Status
             * @enum {string}
             */
            conflict_status: "CLEAR" | "CONFLICTED";
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
            /** Context Version */
            context_version: number;
            /**
             * Record Version
             * @default 1
             */
            record_version: number;
            /**
             * Generated By
             * @default RULE_EVIDENCE_APPLICABILITY_V1
             * @constant
             */
            generated_by: "RULE_EVIDENCE_APPLICABILITY_V1";
            fallback_guidance_context?: components["schemas"]["ActionableFallbackGuidanceContext"] | null;
            /**
             * Legal Obligation
             * @default false
             * @constant
             */
            legal_obligation: false;
        };
        /** RegulatoryDocumentRequirementResult */
        RegulatoryDocumentRequirementResult: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Project Version Id
             * Format: uuid
             */
            project_version_id: string;
            /** Context Version */
            context_version: number;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Data Item Ids
             * @default []
             */
            data_item_ids: string[];
            /**
             * Data Flow Ids
             * @default []
             */
            data_flow_ids: string[];
            /**
             * Scenario Definition Ids
             * @default []
             */
            scenario_definition_ids: string[];
            /**
             * Jurisdiction Ids
             * @default []
             */
            jurisdiction_ids: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /**
             * Stage Kind
             * @default DOCUMENT_REQUIREMENT
             * @constant
             */
            stage_kind: "DOCUMENT_REQUIREMENT";
            /** Upstream Refs */
            upstream_refs: components["schemas"]["AuthorityRef"][];
            /** Items */
            items: components["schemas"]["RequiredDocumentDTOv2"][];
            /**
             * Input Sufficiency
             * @enum {string}
             */
            input_sufficiency: "SUFFICIENT" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN";
            /**
             * Conflict State
             * @enum {string}
             */
            conflict_state: "CLEAR" | "CONFLICTED";
            /** Review Required */
            review_required: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Confidence */
            confidence: string;
            /** Pins */
            pins: components["schemas"]["PinRef"][];
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
            /**
             * Engine Version
             * @default FORMAL_RESULT_AUTHORITY_V2
             * @constant
             */
            engine_version: "FORMAL_RESULT_AUTHORITY_V2";
            provenance: components["schemas"]["AuthorityProvenance"];
            /** Ordinary Status */
            ordinary_status: string;
        };
        /** RequiredDocumentDTOv2 */
        RequiredDocumentDTOv2: {
            /**
             * Document Requirement Id
             * Format: uuid
             */
            document_requirement_id: string;
            /** Document Type Code */
            document_type_code: string;
            /** Name */
            name: string;
            /**
             * Requirement Level
             * @enum {string}
             */
            requirement_level: "REQUIRED" | "CONDITIONAL" | "RECOMMENDED" | "NOT_APPLICABLE";
            /** Trigger Obligation Ids */
            trigger_obligation_ids: string[];
            /** Trigger Cross Border Assessment Ids */
            trigger_cross_border_assessment_ids: string[];
            /** Trigger Path Step Ids */
            trigger_path_step_ids: string[];
            /** Requirement Ids */
            requirement_ids: string[];
            /** Legal Basis Ids */
            legal_basis_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            /** Template Version Id */
            template_version_id: string | null;
            /** Reason Codes */
            reason_codes: string[];
            /** Conditions */
            conditions: components["schemas"]["Condition"][];
            /** Review Required */
            review_required: boolean;
            /**
             * Policy Version Id
             * Format: uuid
             */
            policy_version_id: string;
            /** Input Digest */
            input_digest: string;
            /** Pins Digest */
            pins_digest: string;
        };
        /** RiskAssessmentDTOv2 */
        RiskAssessmentDTOv2: {
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /** Jurisdiction Ids */
            jurisdiction_ids: string[];
            support: components["schemas"]["LegalSupport"];
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Review Required
             * @default false
             */
            review_required: boolean;
            /**
             * Policy Version Ref
             * Format: uuid
             */
            policy_version_ref: string;
            /**
             * Risk Assessment Id
             * Format: uuid
             */
            risk_assessment_id: string;
            /**
             * Candidate Path Id
             * Format: uuid
             */
            candidate_path_id: string;
            /** Dimensions */
            dimensions: components["schemas"]["RiskDimensionResult"][];
            /**
             * Band Conditions
             * @default []
             */
            band_conditions: components["schemas"]["Condition"][];
            /** Score */
            score: string | null;
            risk_level: components["schemas"]["RiskLevel"];
            /** Coverage */
            coverage: string;
            /**
             * Input Sufficiency
             * @enum {string}
             */
            input_sufficiency: "SUFFICIENT" | "INSUFFICIENT_EVIDENCE" | "UNKNOWN";
            /**
             * Score Mode
             * @enum {string}
             */
            score_mode: "WEIGHTED" | "BAND_ONLY";
            /** Decimal Scale */
            decimal_scale: number;
            /**
             * Rounding
             * @enum {string}
             */
            rounding: "ROUND_HALF_EVEN" | "ROUND_HALF_UP" | "ROUND_DOWN";
        };
        /** RiskDimensionResult */
        RiskDimensionResult: {
            /** Code */
            code: string;
            /** Factors */
            factors: components["schemas"]["RiskFactorResult"][];
            /** Score */
            score: string | null;
            band: components["schemas"]["RiskLevel"];
            /** Weight */
            weight: string;
        };
        /** RiskFactorResult */
        RiskFactorResult: {
            /** Code */
            code: string;
            /** Observation Code */
            observation_code: string;
            /** Observed Value */
            observed_value: string | null;
            /** Score */
            score: string | null;
            /** Weight */
            weight: string;
            /** Required */
            required: boolean;
            /** Included */
            included: boolean;
            /** Fact Refs */
            fact_refs: string[];
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" | "UNKNOWN";
        /** Stage1ComplianceResult */
        Stage1ComplianceResult: {
            project: components["schemas"]["ProjectSummary"];
            /** Documents */
            documents: components["schemas"]["DocumentSummary"][];
            /** Data Items */
            data_items: components["schemas"]["DataItemSummary"][];
            /** Flow Nodes */
            flow_nodes: components["schemas"]["FlowNodeSummary"][];
            /** Flows */
            flows: components["schemas"]["FlowSummary"][];
            /**
             * Contract Version
             * @default 2.0
             * @constant
             */
            contract_version: "2.0";
            /**
             * Workflow Run Id
             * Format: uuid
             */
            workflow_run_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING" | "COMPLETED" | "REVIEW_REQUIRED" | "WARNING" | "FAILED" | "CANCELLED";
            /** Graph Version */
            graph_version: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "DATA_AWARE" | "SCENARIO_LEVEL";
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "DATA_ITEM" | "DATA_FLOW" | "SCENARIO";
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Steps */
            steps: string[];
            /** Completed Steps */
            completed_steps: string[];
            /** Current Step */
            current_step: string | null;
            /** Reason Codes */
            reason_codes: string[];
            /** Capability Gaps */
            capability_gaps: string[];
            /** Review Id */
            review_id: string | null;
            /** Classification */
            classification: components["schemas"]["ClassificationResult"][];
            /** Applicability */
            applicability: components["schemas"]["RegulationApplicabilityResult"][];
            obligation: components["schemas"]["DecisionEnvelope_ComplianceObligationDTOv2_"] | null;
            cross_border: components["schemas"]["CrossBorderAssessmentResult"] | null;
            candidate_path: components["schemas"]["DecisionEnvelope_CandidateCompliancePathDTOv2_"] | null;
            risk: components["schemas"]["DecisionEnvelope_RiskAssessmentDTOv2_"] | null;
            recommendation: components["schemas"]["DecisionEnvelope_ComplianceRecommendationDTOv2_"] | null;
            final_path: components["schemas"]["DecisionEnvelope_FinalCompliancePathDTOv2_"] | null;
            document_requirements: components["schemas"]["RegulatoryDocumentRequirementResult"] | null;
            /** Legal Basis */
            legal_basis: components["schemas"]["OfficialLegalBasis"][];
            retrieval: components["schemas"]["RAGContextPack"] | null;
            /**
             * Generation Available
             * @default false
             * @constant
             */
            generation_available: false;
        };
        /** StageRef */
        StageRef: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "APPLICABILITY" | "OBLIGATION" | "CANDIDATE_PATH" | "RISK" | "RECOMMENDATION" | "FINAL_PATH";
            /**
             * Result Id
             * Format: uuid
             */
            result_id: string;
            /** Item Id */
            item_id?: string | null;
            /** Content Digest */
            content_digest: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowStart */
        WorkflowStart: Record<string, never>;
        /** WorkflowView */
        WorkflowView: {
            /**
             * Workflow Run Id
             * Format: uuid
             */
            workflow_run_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "RUNNING" | "COMPLETED" | "REVIEW_REQUIRED" | "WARNING" | "FAILED" | "CANCELLED";
            /** Current Step */
            current_step?: string | null;
            /** Result Refs */
            result_refs?: {
                [key: string]: string[];
            };
            /**
             * Reason Codes
             * @default []
             */
            reason_codes: string[];
            /** Review Id */
            review_id?: string | null;
            /** Fallback Ref */
            fallback_ref?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    stage1_result_api_v1_workflows__run_id__stage1_result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stage1ComplianceResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
