/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_v1_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Review */
        get: operations["read_review_api_v1_reviews__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide */
        post: operations["decide_api_v1_reviews__review_id__decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct */
        post: operations["correct_api_v1_reviews__review_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_reviews__review_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reviews/{review_id}/successor/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Continue Successor */
        post: operations["continue_successor_api_v1_reviews__review_id__successor_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FactSelection */
        FactSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            correction_type: "SELECT_BUSINESS_FACT";
            /**
             * Target Object Type
             * @constant
             */
            target_object_type: "CONTEXT_CONFLICT";
            /**
             * Target Object Id
             * Format: uuid
             */
            target_object_id: string;
            /**
             * Selected Fact Id
             * Format: uuid
             */
            selected_fact_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntakeClarification */
        IntakeClarification: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            correction_type: "CLARIFY_INTAKE";
            /**
             * Target Object Type
             * @constant
             */
            target_object_type: "PROJECT_INTAKE";
            /**
             * Target Object Id
             * Format: uuid
             */
            target_object_id: string;
            facts: components["schemas"]["IntakeFacts"];
        };
        /** IntakeFacts */
        IntakeFacts: {
            /** Industry */
            industry?: string | null;
            /** Business Scenario */
            business_scenario?: string | null;
            /** Scenario Description */
            scenario_description?: string | null;
            /** Selected Product Domains */
            selected_product_domains?: string[];
            /** Selected Products */
            selected_products?: string[];
            /** Source Locations */
            source_locations?: string[];
            /** Destination Locations */
            destination_locations?: string[];
            /** Processing Locations */
            processing_locations?: string[];
            /** Storage Locations */
            storage_locations?: string[];
            /** Data Flow Description */
            data_flow_description?: string | null;
            /** Data Categories */
            data_categories?: string[];
            /** Data Volume */
            data_volume?: string | null;
            /** Business Purpose */
            business_purpose?: string | null;
            /** Organizations */
            organizations?: string[];
            /** Third Parties */
            third_parties?: string[];
            /** Uploaded Documents */
            uploaded_documents?: string[];
            /** Requested Outputs */
            requested_outputs?: string[];
            /**
             * Analysis As Of Date
             * Format: date
             */
            analysis_as_of_date: string;
        };
        /** ProductSelection */
        ProductSelection: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            correction_type: "SELECT_PRODUCT_SCOPE";
            /**
             * Target Object Type
             * @constant
             */
            target_object_type: "CONTEXT_CONFLICT";
            /**
             * Target Object Id
             * Format: uuid
             */
            target_object_id: string;
            /** Selected Product Ids */
            selected_product_ids: string[];
        };
        /** ProvenanceDTO */
        ProvenanceDTO: {
            /** Source Type */
            source_type: string;
            /** Source Ref */
            source_ref: string;
            /** Source Version */
            source_version?: string | null;
            /** Source Locator */
            source_locator?: string | null;
            /** Actor Ref */
            actor_ref?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Correlation Id */
            correlation_id?: string | null;
            /** Generated By */
            generated_by: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /** Evidence Ids */
            evidence_ids?: string[];
        };
        /** ReviewChoice */
        ReviewChoice: {
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Object Type */
            object_type: string;
            /** Display Value */
            display_value: string;
            /**
             * Source Trace Ids
             * @default []
             */
            source_trace_ids: string[];
            /**
             * Source Document Ids
             * @default []
             */
            source_document_ids: string[];
            /**
             * Structured Provenance
             * @default []
             */
            structured_provenance: components["schemas"]["ProvenanceDTO"][];
        };
        /** ReviewCorrectionRequest */
        ReviewCorrectionRequest: {
            /** Expected Record Version */
            expected_record_version: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Correction */
            correction: components["schemas"]["FactSelection"] | components["schemas"]["ProductSelection"] | components["schemas"]["IntakeClarification"];
            /** Comment */
            comment?: string | null;
        };
        /**
         * ReviewDecisionCode
         * @enum {string}
         */
        ReviewDecisionCode: "APPROVE" | "REJECT" | "REQUEST_CHANGES";
        /** ReviewDecisionRequest */
        ReviewDecisionRequest: {
            decision: components["schemas"]["ReviewDecisionCode"];
            /** Expected Record Version */
            expected_record_version: number;
            /** Idempotency Key */
            idempotency_key: string;
            /** Comment */
            comment?: string | null;
        };
        /** ReviewHistoryItem */
        ReviewHistoryItem: {
            /**
             * Decision Id
             * Format: uuid
             */
            decision_id: string;
            decision: components["schemas"]["ReviewDecisionCode"];
            /** Comment */
            comment: string | null;
            /** Decided By */
            decided_by: string;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
        };
        /** ReviewLineage */
        ReviewLineage: {
            /**
             * Correction Id
             * Format: uuid
             */
            correction_id: string;
            /**
             * Source Review Id
             * Format: uuid
             */
            source_review_id: string;
            /**
             * Source Workflow Run Id
             * Format: uuid
             */
            source_workflow_run_id: string;
            /**
             * Source Snapshot Id
             * Format: uuid
             */
            source_snapshot_id: string;
            /**
             * Successor Project Version Id
             * Format: uuid
             */
            successor_project_version_id: string;
            /**
             * Successor Snapshot Id
             * Format: uuid
             */
            successor_snapshot_id: string;
            /**
             * Successor Workflow Run Id
             * Format: uuid
             */
            successor_workflow_run_id: string;
            /** Correction Type */
            correction_type: string;
            /** Submitted By */
            submitted_by: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Comment */
            comment?: string | null;
            /**
             * Rerun From Stage
             * @default requirement
             * @constant
             */
            rerun_from_stage: "requirement";
        };
        /** ReviewPage */
        ReviewPage: {
            /** Items */
            items: components["schemas"]["ReviewView"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * ReviewResumeRequest
         * @description Body-free or empty typed transport; server reconstructs resume authority.
         */
        ReviewResumeRequest: Record<string, never>;
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "NOT_REQUIRED" | "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED";
        /** ReviewView */
        ReviewView: {
            /**
             * Review Id
             * Format: uuid
             */
            review_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Analysis Snapshot Id
             * Format: uuid
             */
            analysis_snapshot_id: string;
            /**
             * Workflow Run Id
             * Format: uuid
             */
            workflow_run_id: string;
            /** Review Type */
            review_type: string;
            /** Reason Codes */
            reason_codes: string[];
            /** Reason Summary */
            reason_summary: string;
            /** Object Type */
            object_type: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Owning Stage */
            owning_stage: string | null;
            status: components["schemas"]["ReviewStatus"];
            /**
             * Presentation State
             * @enum {string}
             */
            presentation_state: "PENDING" | "CHANGES_REQUESTED" | "APPROVED" | "REJECTED" | "CANCELLED" | "SUPERSEDED";
            /** Allowed Actions */
            allowed_actions: string[];
            /**
             * Resolution Mode
             * @enum {string}
             */
            resolution_mode: "SAME_SNAPSHOT" | "SUCCESSOR_SNAPSHOT" | "UNAVAILABLE";
            /** Required Role */
            required_role: string;
            /**
             * Continuation Status
             * @default NOT_AVAILABLE
             * @enum {string}
             */
            continuation_status: "NOT_AVAILABLE" | "RESUME_PENDING" | "CONTINUED";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Record Version */
            record_version: number;
            /**
             * Evidence Refs
             * @default []
             */
            evidence_refs: string[];
            /**
             * Legal Basis Refs
             * @default []
             */
            legal_basis_refs: string[];
            /**
             * Choices
             * @default []
             */
            choices: components["schemas"]["ReviewChoice"][];
            /**
             * History
             * @default []
             */
            history: components["schemas"]["ReviewHistoryItem"][];
            lineage?: components["schemas"]["ReviewLineage"] | null;
            /** Capability Gap */
            capability_gap?: string | null;
            intake_facts?: components["schemas"]["IntakeFacts"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_reviews_api_v1_reviews_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ReviewStatus"] | null;
                project_id?: string | null;
                review_type?: string | null;
                owning_stage?: string | null;
                created_after?: string | null;
                created_before?: string | null;
                offset?: number;
                limit?: number;
                order?: "CREATED_DESC" | "CREATED_ASC";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_review_api_v1_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_v1_reviews__review_id__decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_api_v1_reviews__review_id__corrections_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewLineage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_v1_reviews__review_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewResumeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    continue_successor_api_v1_reviews__review_id__successor_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewResumeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
