/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/integration-clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Clients */
        get: operations["clients_api_v1_admin_integration_clients_get"];
        put?: never;
        /** Create Client */
        post: operations["create_client_api_v1_admin_integration_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/integration-clients/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_v1_admin_integration_clients_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}/project-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bindings */
        get: operations["bindings_api_v1_admin_integration_clients__client_id__project_bindings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Client */
        patch: operations["update_client_api_v1_admin_integration_clients__client_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}/rotate-credential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate */
        post: operations["rotate_api_v1_admin_integration_clients__client_id__rotate_credential_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}/project-binding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Bind */
        put: operations["bind_api_v1_admin_integration_clients__client_id__project_binding_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}/webhook-subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Subscriptions */
        get: operations["admin_subscriptions_api_v1_admin_integration_clients__client_id__webhook_subscriptions_get"];
        put?: never;
        /** Admin Create Subscription */
        post: operations["admin_create_subscription_api_v1_admin_integration_clients__client_id__webhook_subscriptions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}/webhook-subscriptions/{subscription_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Admin Change Subscription */
        patch: operations["admin_change_subscription_api_v1_admin_integration_clients__client_id__webhook_subscriptions__subscription_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}/webhook-subscriptions/{subscription_id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Rotate Subscription */
        post: operations["admin_rotate_subscription_api_v1_admin_integration_clients__client_id__webhook_subscriptions__subscription_id__rotate_secret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}/webhook-subscriptions/{subscription_id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Deliveries */
        get: operations["admin_deliveries_api_v1_admin_integration_clients__client_id__webhook_subscriptions__subscription_id__deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/integration-clients/{client_id}/webhook-subscriptions/{subscription_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin Test */
        post: operations["admin_test_api_v1_admin_integration_clients__client_id__webhook_subscriptions__subscription_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClientCreate */
        ClientCreate: {
            /** Display Name */
            display_name: string;
            /** Allowed Scopes */
            allowed_scopes: components["schemas"]["IntegrationScope"][];
            /**
             * Credential Type
             * @default OAUTH2
             */
            credential_type: string;
        };
        /** ClientCredentialView */
        ClientCredentialView: {
            client: components["schemas"]["ClientView"];
            /**
             * Credential Id
             * Format: uuid
             */
            credential_id: string;
            /** Credential */
            credential?: string | null;
        };
        /** ClientUpdate */
        ClientUpdate: {
            /** Expected Version */
            expected_version: number;
            /** Status */
            status: string;
            /** Allowed Scopes */
            allowed_scopes?: components["schemas"]["IntegrationScope"][] | null;
        };
        /** ClientView */
        ClientView: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Display Name */
            display_name: string;
            /** Status */
            status: string;
            /** Allowed Scopes */
            allowed_scopes: components["schemas"]["IntegrationScope"][];
            /** Credential Type */
            credential_type: string;
            /** Record Version */
            record_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Last Used At */
            last_used_at?: string | null;
            /** Credential Configured */
            credential_configured: boolean;
        };
        /** DeliveryAccepted */
        DeliveryAccepted: {
            /**
             * Delivery Id
             * Format: uuid
             */
            delivery_id: string;
            /** Status */
            status: string;
        };
        /** DeliveryView */
        DeliveryView: {
            /**
             * Delivery Id
             * Format: uuid
             */
            delivery_id: string;
            /**
             * Subscription Id
             * Format: uuid
             */
            subscription_id: string;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Status */
            status: string;
            /** Attempts */
            attempts: number;
            /** Last Status Code */
            last_status_code: number | null;
            /** Error Code */
            error_code: string | null;
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
        };
        /** EmptyCommand */
        EmptyCommand: Record<string, never>;
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegrationOptions */
        IntegrationOptions: {
            /** Scopes */
            scopes: components["schemas"]["IntegrationScope"][];
            /** Webhook Events */
            webhook_events: string[];
            /**
             * Credential Types
             * @default [
             *       "OAUTH2",
             *       "SERVICE_ACCOUNT"
             *     ]
             */
            credential_types: string[];
            /**
             * Deployment Classes
             * @default [
             *       "EXTERNAL",
             *       "INTERNAL"
             *     ]
             */
            deployment_classes: string[];
        };
        /**
         * IntegrationScope
         * @enum {string}
         */
        IntegrationScope: "project:create" | "project:read" | "intake:write" | "document:upload" | "compliance:analyze" | "compliance:read" | "model:select" | "webhook:manage";
        /** ProjectBindingCommand */
        ProjectBindingCommand: {
            /** Expected Version */
            expected_version: number;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Status
             * @default ACTIVE
             */
            status: string;
        };
        /** ProjectBindingView */
        ProjectBindingView: {
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** Binding Type */
            binding_type: string;
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionCommand */
        VersionCommand: {
            /** Expected Version */
            expected_version: number;
        };
        /** WebhookCreate */
        WebhookCreate: {
            /** Callback Url */
            callback_url: string;
            /** Event Codes */
            event_codes: string[];
            /**
             * Deployment Class
             * @default EXTERNAL
             */
            deployment_class: string;
        };
        /** WebhookSecretView */
        WebhookSecretView: {
            subscription: components["schemas"]["WebhookView"];
            /** Secret */
            secret?: string | null;
        };
        /** WebhookUpdate */
        WebhookUpdate: {
            /** Expected Version */
            expected_version: number;
            /** Enabled */
            enabled: boolean;
            /** Callback Url */
            callback_url?: string | null;
            /** Event Codes */
            event_codes?: string[] | null;
        };
        /** WebhookView */
        WebhookView: {
            /**
             * Subscription Id
             * Format: uuid
             */
            subscription_id: string;
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Callback Url */
            callback_url: string;
            /** Event Codes */
            event_codes: string[];
            /** Enabled */
            enabled: boolean;
            /** Record Version */
            record_version: number;
            /** Secret Configured */
            secret_configured: boolean;
            /**
             * Deployment Class
             * @default EXTERNAL
             */
            deployment_class: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clients_api_v1_admin_integration_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientView"][];
                };
            };
        };
    };
    create_client_api_v1_admin_integration_clients_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientCredentialView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_api_v1_admin_integration_clients_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationOptions"];
                };
            };
        };
    };
    bindings_api_v1_admin_integration_clients__client_id__project_bindings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectBindingView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_api_v1_admin_integration_clients__client_id__patch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_api_v1_admin_integration_clients__client_id__rotate_credential_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientCredentialView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_api_v1_admin_integration_clients__client_id__project_binding_put: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectBindingCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_subscriptions_api_v1_admin_integration_clients__client_id__webhook_subscriptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_create_subscription_api_v1_admin_integration_clients__client_id__webhook_subscriptions_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSecretView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_change_subscription_api_v1_admin_integration_clients__client_id__webhook_subscriptions__subscription_id__patch: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                client_id: string;
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_rotate_subscription_api_v1_admin_integration_clients__client_id__webhook_subscriptions__subscription_id__rotate_secret_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                client_id: string;
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSecretView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_deliveries_api_v1_admin_integration_clients__client_id__webhook_subscriptions__subscription_id__deliveries_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_test_api_v1_admin_integration_clients__client_id__webhook_subscriptions__subscription_id__test_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                client_id: string;
                subscription_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmptyCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
