/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/model-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Providers */
        get: operations["providers_api_v1_admin_model_providers_get"];
        put?: never;
        /** Save Provider */
        post: operations["save_provider_api_v1_admin_model_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-providers/versions/{version_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider Transition */
        post: operations["provider_transition_api_v1_admin_model_providers_versions__version_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-providers/{provider_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Provider Enabled */
        put: operations["provider_enabled_api_v1_admin_model_providers__provider_id__enabled_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-providers/versions/{version_id}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Connection */
        post: operations["test_connection_api_v1_admin_model_providers_versions__version_id__test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-providers/versions/{version_id}/discover-models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover Models */
        post: operations["discover_models_api_v1_admin_model_providers_versions__version_id__discover_models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-providers/{provider_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_admin_model_providers__provider_id__models_get"];
        put?: never;
        /** Save Model */
        post: operations["save_model_api_v1_admin_model_providers__provider_id__models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-providers/models/deployments/{deployment_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Model Transition */
        post: operations["model_transition_api_v1_admin_model_providers_models_deployments__deployment_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-providers/models/{model_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Model Enabled */
        put: operations["model_enabled_api_v1_admin_model_providers_models__model_id__enabled_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/model-providers/models/deployments/{deployment_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Model */
        post: operations["test_model_api_v1_admin_model_providers_models_deployments__deployment_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ControlEnabled */
        ControlEnabled: {
            /** Enabled */
            enabled: boolean;
            /** Expected Record Version */
            expected_record_version: number;
        };
        /** ControlTransition */
        ControlTransition: {
            target_status: components["schemas"]["GovernanceStatus"];
            /** Expected Record Version */
            expected_record_version: number;
        };
        /** EnabledView */
        EnabledView: {
            /** Enabled */
            enabled: boolean;
            /** Record Version */
            record_version: number;
        };
        /**
         * GovernanceStatus
         * @enum {string}
         */
        GovernanceStatus: "DRAFT" | "PENDING_REVIEW" | "APPROVED" | "ACTIVE" | "SUPERSEDED" | "EXPIRED" | "ARCHIVED";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ModelCapabilityCode
         * @enum {string}
         */
        ModelCapabilityCode: "TEXT" | "VISION" | "STRUCTURED_OUTPUT" | "LONG_CONTEXT" | "EMBEDDING" | "RERANK";
        /** ModelDraft */
        ModelDraft: {
            /** Model Id */
            model_id?: string | null;
            /** Expected Record Version */
            expected_record_version?: number | null;
            /**
             * Provider Version Id
             * Format: uuid
             */
            provider_version_id: string;
            /** Remote Model Name */
            remote_model_name: string;
            /** Display Name */
            display_name: string;
            /** Capabilities */
            capabilities: components["schemas"]["ModelCapabilityCode"][];
            /** Operations */
            operations: components["schemas"]["ModelOperation"][];
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Embedding Dimension */
            embedding_dimension?: number | null;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Structured Output Format
             * @default json_schema
             * @enum {string}
             */
            structured_output_format: "json_schema" | "json_object";
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
        };
        /** ModelListView */
        ModelListView: {
            /** Models */
            models: components["schemas"]["ModelView"][];
        };
        /**
         * ModelOperation
         * @enum {string}
         */
        ModelOperation: "chat" | "chat_stream" | "structured_output" | "embedding" | "rerank" | "count_tokens" | "health_check";
        /** ModelTestRequest */
        ModelTestRequest: {
            /**
             * Operation
             * @default chat
             * @enum {string}
             */
            operation: "chat" | "structured_output" | "embedding";
        };
        /** ModelView */
        ModelView: {
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
            /**
             * Deployment Id
             * Format: uuid
             */
            deployment_id: string;
            /**
             * Provider Version Id
             * Format: uuid
             */
            provider_version_id: string;
            /** Display Name */
            display_name: string;
            /** Remote Model Name */
            remote_model_name: string;
            /** Capabilities */
            capabilities: components["schemas"]["ModelCapabilityCode"][];
            /** Operations */
            operations: components["schemas"]["ModelOperation"][];
            /** Max Output Tokens */
            max_output_tokens: number;
            /** Embedding Dimension */
            embedding_dimension: number | null;
            /** Priority */
            priority: number;
            /**
             * Structured Output Format
             * @enum {string}
             */
            structured_output_format: "json_schema" | "json_object";
            /** Enabled */
            enabled: boolean;
            lifecycle_status: components["schemas"]["GovernanceStatus"];
            /** Record Version */
            record_version: number;
            /** Model Record Version */
            model_record_version: number;
            /** Health Status */
            health_status: string;
        };
        /** ProviderDraft */
        ProviderDraft: {
            /** Provider Id */
            provider_id?: string | null;
            /** Expected Record Version */
            expected_record_version?: number | null;
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /**
             * Vendor Preset
             * @default OTHER_OPENAI_COMPATIBLE
             */
            vendor_preset: string;
            /**
             * Protocol
             * @default OPENAI_COMPATIBLE
             * @enum {string}
             */
            protocol: "OPENAI_COMPATIBLE" | "GENERIC_REST";
            /** Base Url */
            base_url: string;
            /**
             * Deployment Class
             * @default EXTERNAL
             * @enum {string}
             */
            deployment_class: "EXTERNAL" | "PRIVATE_CLOUD" | "ON_PREMISE";
            /** Trust Level */
            trust_level: string;
            /** Data Boundary */
            data_boundary: string;
            /** Credential */
            credential?: string | null;
            /**
             * Timeout Seconds
             * @default 30
             */
            timeout_seconds: number;
            /**
             * Health Ttl Seconds
             * @default 300
             */
            health_ttl_seconds: number;
            /**
             * Effective From
             * Format: date
             */
            effective_from: string;
            /** Effective To */
            effective_to?: string | null;
        };
        /** ProviderListView */
        ProviderListView: {
            /** Providers */
            providers: components["schemas"]["ProviderView"][];
        };
        /** ProviderTestResult */
        ProviderTestResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "HEALTHY" | "AUTHENTICATION_FAILED" | "ENDPOINT_UNREACHABLE" | "TLS_ERROR" | "MODEL_ENDPOINT_INVALID" | "CAPABILITY_UNSUPPORTED" | "SECRET_UNAVAILABLE" | "TIMEOUT";
            /**
             * Candidate Models
             * @default []
             */
            candidate_models: string[];
        };
        /** ProviderVersionView */
        ProviderVersionView: {
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
            /**
             * Provider Version Id
             * Format: uuid
             */
            provider_version_id: string;
            /** Provider Version */
            provider_version: number;
            /** Display Name */
            display_name: string;
            /** Vendor Preset */
            vendor_preset: string;
            /** Protocol */
            protocol: string;
            /** Base Url */
            base_url: string | null;
            /** Deployment Class */
            deployment_class: string;
            /** Trust Level */
            trust_level: string;
            /** Data Boundary */
            data_boundary: string;
            /** Secret Configured */
            secret_configured: boolean;
            /** Enabled */
            enabled: boolean;
            lifecycle_status: components["schemas"]["GovernanceStatus"];
            /** Record Version */
            record_version: number;
            /** Effective From */
            effective_from: string | null;
            /** Effective To */
            effective_to: string | null;
        };
        /** ProviderView */
        ProviderView: {
            /**
             * Provider Id
             * Format: uuid
             */
            provider_id: string;
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Record Version */
            record_version: number;
            /** Active Version Id */
            active_version_id: string | null;
            /** Versions */
            versions: components["schemas"]["ProviderVersionView"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    providers_api_v1_admin_model_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListView"];
                };
            };
        };
    };
    save_provider_api_v1_admin_model_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderVersionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_transition_api_v1_admin_model_providers_versions__version_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlTransition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderVersionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_enabled_api_v1_admin_model_providers__provider_id__enabled_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlEnabled"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnabledView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_v1_admin_model_providers_versions__version_id__test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discover_models_api_v1_admin_model_providers_versions__version_id__discover_models_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_api_v1_admin_model_providers__provider_id__models_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelListView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_model_api_v1_admin_model_providers__provider_id__models_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_transition_api_v1_admin_model_providers_models_deployments__deployment_id__transition_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlTransition"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_enabled_api_v1_admin_model_providers_models__model_id__enabled_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlEnabled"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnabledView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_model_api_v1_admin_model_providers_models_deployments__deployment_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deployment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
