"""Phase 1G derived retrieval/evidence governance (frozen DDL)."""

from alembic import op

revision = "0007_phase1g"
down_revision = "0006_phase1f"
branch_labels = None
depends_on = None
UPGRADE_STATEMENTS = [
    "\nCREATE TABLE knowledge_sufficiency_policies (\n\tpolicy_version_id VARCHAR(36) NOT NULL, \n\tpolicy_id VARCHAR(36) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tlifecycle VARCHAR(30) NOT NULL, \n\tpayload_json JSON NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (policy_version_id), \n\tCONSTRAINT uq_sufficiency_policy_version UNIQUE (tenant_id, policy_id, version), \n\tCONSTRAINT ck_sufficiency_lifecycle CHECK (lifecycle IN ('DRAFT','ACTIVE','SUPERSEDED')), \n\tCONSTRAINT ck_sufficiency_version CHECK (version > 0)\n)\n\n",
    "\nCREATE TABLE retrieval_policies (\n\tpolicy_version_id VARCHAR(36) NOT NULL, \n\tpolicy_id VARCHAR(36) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tlifecycle VARCHAR(30) NOT NULL, \n\tpayload_json JSON NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (policy_version_id), \n\tCONSTRAINT uq_retrieval_policy_version UNIQUE (tenant_id, policy_id, version), \n\tCONSTRAINT ck_retrieval_lifecycle CHECK (lifecycle IN ('DRAFT','ACTIVE','SUPERSEDED')), \n\tCONSTRAINT ck_retrieval_version CHECK (version > 0)\n)\n\n",
    "\nCREATE TABLE trusted_source_policies (\n\tpolicy_version_id VARCHAR(36) NOT NULL, \n\tpolicy_id VARCHAR(36) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tlifecycle VARCHAR(30) NOT NULL, \n\tpayload_json JSON NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (policy_version_id), \n\tCONSTRAINT uq_trusted_source_policy_version UNIQUE (tenant_id, policy_id, version), \n\tCONSTRAINT ck_trusted_source_lifecycle CHECK (lifecycle IN ('DRAFT','ACTIVE','SUPERSEDED')), \n\tCONSTRAINT ck_trusted_source_version CHECK (version > 0)\n)\n\n",
    "\nCREATE TABLE wiki_pages (\n\twiki_page_id VARCHAR(36) NOT NULL, \n\ttitle VARCHAR(250) NOT NULL, \n\tlegal_basis BOOLEAN NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (wiki_page_id), \n\tCONSTRAINT ck_wiki_not_legal_basis CHECK (NOT legal_basis)\n)\n\n",
    "\nCREATE TABLE wiki_versions (\n\twiki_version_id VARCHAR(36) NOT NULL, \n\twiki_page_id VARCHAR(36) NOT NULL, \n\tversion INTEGER NOT NULL, \n\tcontent TEXT NOT NULL, \n\tcontent_hash VARCHAR(64) NOT NULL, \n\tlifecycle VARCHAR(30) NOT NULL, \n\tgenerated_by VARCHAR(160) NOT NULL, \n\treviewed_by VARCHAR(160), \n\tofficial_evidence BOOLEAN NOT NULL, \n\tlegal_basis BOOLEAN NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (wiki_version_id), \n\tCONSTRAINT uq_wiki_version UNIQUE (tenant_id, wiki_page_id, version), \n\tCONSTRAINT ck_wiki_derived CHECK (NOT official_evidence AND NOT legal_basis), \n\tCONSTRAINT ck_wiki_lifecycle CHECK (lifecycle IN ('DRAFT','VALIDATED','PENDING_REVIEW','APPROVED','ACTIVE','SUPERSEDED')), \n\tCONSTRAINT ck_wiki_review_boundary CHECK (lifecycle NOT IN ('APPROVED','ACTIVE') OR (reviewed_by IS NOT NULL AND reviewed_by<>generated_by)), \n\tFOREIGN KEY(wiki_page_id) REFERENCES wiki_pages (wiki_page_id)\n)\n\n",
    "\nCREATE TABLE retrieval_runs (\n\tretrieval_run_id VARCHAR(36) NOT NULL, \n\tproject_id VARCHAR(36) NOT NULL, \n\tanalysis_snapshot_id VARCHAR(36) NOT NULL, \n\tpolicy_version_id VARCHAR(36) NOT NULL, \n\towner_actor_id VARCHAR(160) NOT NULL, \n\tidempotency_key VARCHAR(120) NOT NULL, \n\trequest_hash VARCHAR(64) NOT NULL, \n\tquery_json JSON NOT NULL, \n\tplan_json JSON NOT NULL, \n\ttraces_json JSON NOT NULL, \n\tstatistics_json JSON NOT NULL, \n\terror_code VARCHAR(100), \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (retrieval_run_id), \n\tCONSTRAINT uq_retrieval_idempotency UNIQUE (tenant_id, project_id, idempotency_key), \n\tCONSTRAINT ck_retrieval_run_status CHECK (status IN ('RUNNING','COMPLETED','FAILED')), \n\tFOREIGN KEY(project_id) REFERENCES projects (project_id), \n\tFOREIGN KEY(analysis_snapshot_id) REFERENCES analysis_snapshots (analysis_snapshot_id), \n\tFOREIGN KEY(policy_version_id) REFERENCES retrieval_policies (policy_version_id)\n)\n\n",
    "\nCREATE TABLE wiki_publish_records (\n\tpublish_record_id VARCHAR(36) NOT NULL, \n\twiki_version_id VARCHAR(36) NOT NULL, \n\tpublished_by VARCHAR(160) NOT NULL, \n\tpublished_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (publish_record_id), \n\tCONSTRAINT uq_wiki_publish UNIQUE (wiki_version_id), \n\tFOREIGN KEY(wiki_version_id) REFERENCES wiki_versions (wiki_version_id)\n)\n\n",
    "\nCREATE TABLE wiki_reviews (\n\twiki_review_id VARCHAR(36) NOT NULL, \n\twiki_version_id VARCHAR(36) NOT NULL, \n\treview_task_id VARCHAR(36) NOT NULL, \n\treviewer VARCHAR(160), \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (wiki_review_id), \n\tCONSTRAINT uq_wiki_review UNIQUE (wiki_version_id), \n\tFOREIGN KEY(wiki_version_id) REFERENCES wiki_versions (wiki_version_id), \n\tFOREIGN KEY(review_task_id) REFERENCES admin_review_tasks (review_task_id)\n)\n\n",
    "\nCREATE TABLE evidence_packs (\n\tevidence_pack_id VARCHAR(36) NOT NULL, \n\tretrieval_run_id VARCHAR(36) NOT NULL, \n\tanalysis_snapshot_id VARCHAR(36) NOT NULL, \n\tmanifest_json JSON NOT NULL, \n\tcontext_pack_json JSON NOT NULL, \n\tderived BOOLEAN NOT NULL, \n\tlegal_source_of_truth BOOLEAN NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (evidence_pack_id), \n\tCONSTRAINT uq_retrieval_pack UNIQUE (retrieval_run_id), \n\tCONSTRAINT ck_pack_derived CHECK (derived AND NOT legal_source_of_truth), \n\tFOREIGN KEY(retrieval_run_id) REFERENCES retrieval_runs (retrieval_run_id), \n\tFOREIGN KEY(analysis_snapshot_id) REFERENCES analysis_snapshots (analysis_snapshot_id)\n)\n\n",
    "\nCREATE TABLE external_evidence_candidates (\n\tcandidate_id VARCHAR(36) NOT NULL, \n\tretrieval_run_id VARCHAR(36) NOT NULL, \n\tsource_id VARCHAR(36) NOT NULL, \n\tpayload_json JSON NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (candidate_id), \n\tFOREIGN KEY(retrieval_run_id) REFERENCES retrieval_runs (retrieval_run_id), \n\tFOREIGN KEY(source_id) REFERENCES knowledge_source_definitions (knowledge_source_definition_id)\n)\n\n",
    "\nCREATE TABLE external_evidence_validation_results (\n\tvalidation_result_id VARCHAR(36) NOT NULL, \n\tcandidate_id VARCHAR(36) NOT NULL, \n\tresult_json JSON NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (validation_result_id), \n\tCONSTRAINT ck_external_validation CHECK (status IN ('VERIFIED','REJECTED','DISCOVERY_ONLY')), \n\tFOREIGN KEY(candidate_id) REFERENCES external_evidence_candidates (candidate_id)\n)\n\n",
    "\nCREATE TABLE knowledge_sufficiency_results (\n\tsufficiency_result_id VARCHAR(36) NOT NULL, \n\tevidence_pack_id VARCHAR(36) NOT NULL, \n\tpolicy_version_id VARCHAR(36) NOT NULL, \n\tresult_json JSON NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (sufficiency_result_id), \n\tCONSTRAINT uq_pack_sufficiency UNIQUE (evidence_pack_id), \n\tCONSTRAINT ck_sufficiency_status CHECK (status IN ('SUFFICIENT','PARTIALLY_SUFFICIENT','INSUFFICIENT','CONFLICTED')), \n\tFOREIGN KEY(evidence_pack_id) REFERENCES evidence_packs (evidence_pack_id), \n\tFOREIGN KEY(policy_version_id) REFERENCES knowledge_sufficiency_policies (policy_version_id)\n)\n\n",
    "\nCREATE TABLE runtime_verified_external_evidence (\n\texternal_evidence_id VARCHAR(36) NOT NULL, \n\tanalysis_snapshot_id VARCHAR(36) NOT NULL, \n\tsource_id VARCHAR(36) NOT NULL, \n\ttrusted_policy_version_id VARCHAR(36) NOT NULL, \n\tretrieval_policy_version_id VARCHAR(36) NOT NULL, \n\tsufficiency_policy_version_id VARCHAR(36) NOT NULL, \n\tcandidate_id VARCHAR(36) NOT NULL, \n\tcontent_hash VARCHAR(64) NOT NULL, \n\toriginal_content BYTEA NOT NULL, \n\tpayload_json JSON NOT NULL, \n\tactive_knowledge BOOLEAN NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (external_evidence_id), \n\tCONSTRAINT uq_snapshot_external_source UNIQUE (tenant_id, analysis_snapshot_id, source_id, trusted_policy_version_id), \n\tCONSTRAINT ck_runtime_external_not_active CHECK (status='VERIFIED' AND NOT active_knowledge), \n\tFOREIGN KEY(analysis_snapshot_id) REFERENCES analysis_snapshots (analysis_snapshot_id), \n\tFOREIGN KEY(source_id) REFERENCES knowledge_source_definitions (knowledge_source_definition_id), \n\tFOREIGN KEY(trusted_policy_version_id) REFERENCES trusted_source_policies (policy_version_id), \n\tFOREIGN KEY(retrieval_policy_version_id) REFERENCES retrieval_policies (policy_version_id), \n\tFOREIGN KEY(sufficiency_policy_version_id) REFERENCES knowledge_sufficiency_policies (policy_version_id), \n\tFOREIGN KEY(candidate_id) REFERENCES external_evidence_candidates (candidate_id)\n)\n\n",
    "\nCREATE TABLE wiki_source_bindings (\n\tsource_binding_id VARCHAR(36) NOT NULL, \n\twiki_version_id VARCHAR(36) NOT NULL, \n\tknowledge_version_id VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (source_binding_id), \n\tCONSTRAINT uq_wiki_source UNIQUE (wiki_version_id, knowledge_version_id), \n\tFOREIGN KEY(wiki_version_id) REFERENCES wiki_versions (wiki_version_id), \n\tFOREIGN KEY(knowledge_version_id) REFERENCES knowledge_document_versions (knowledge_version_id)\n)\n\n",
    "\nCREATE TABLE knowledge_runtime_publications (\n\tknowledge_version_id VARCHAR(36) NOT NULL, \n\tpublication_event_id VARCHAR(36) NOT NULL, \n\tevent_version INTEGER NOT NULL, \n\tpolicy_version_id VARCHAR(36), \n\tindex_version_id VARCHAR(36), \n\tembedding_config_id VARCHAR(36), \n\tregistry_projection_version VARCHAR(64), \n\tcache_generation VARCHAR(100), \n\tchecks_json JSON NOT NULL, \n\tassets_json JSON NOT NULL, \n\treason_codes_json JSON NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (knowledge_version_id), \n\tCONSTRAINT uq_runtime_publication_event UNIQUE (publication_event_id), \n\tCONSTRAINT ck_runtime_publication_status CHECK (status IN ('PENDING','BUILDING','READY','FAILED')), \n\tCONSTRAINT ck_runtime_ready_barrier CHECK (status<>'READY' OR (index_version_id IS NOT NULL AND registry_projection_version IS NOT NULL AND cache_generation IS NOT NULL)), \n\tFOREIGN KEY(knowledge_version_id) REFERENCES knowledge_document_versions (knowledge_version_id), \n\tFOREIGN KEY(publication_event_id) REFERENCES registry_sync_events (registry_sync_event_id), \n\tFOREIGN KEY(policy_version_id) REFERENCES retrieval_policies (policy_version_id), \n\tFOREIGN KEY(index_version_id) REFERENCES knowledge_index_versions (index_version_id), \n\tFOREIGN KEY(embedding_config_id) REFERENCES model_deployments (model_deployment_id)\n)\n\n",
    "\nCREATE TABLE knowledge_graph_nodes (\n\tsource_knowledge_id VARCHAR(36) NOT NULL, \n\tsource_knowledge_version_id VARCHAR(36) NOT NULL, \n\tsource_evidence_id VARCHAR(36) NOT NULL, \n\tjurisdiction_id VARCHAR(36) NOT NULL, \n\tpayload_json JSON NOT NULL, \n\tgenerated_by VARCHAR(160) NOT NULL, \n\treviewed_by VARCHAR(160), \n\treview_task_id VARCHAR(36), \n\tderived BOOLEAN NOT NULL, \n\tlegal_applicability BOOLEAN NOT NULL, \n\tgraph_node_id VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (graph_node_id), \n\tCONSTRAINT ck_graph_node_derived CHECK (derived AND NOT legal_applicability), \n\tCONSTRAINT ck_graph_node_status CHECK (status IN ('DRAFT','ACTIVE','ARCHIVED')), \n\tCONSTRAINT ck_graph_node_review CHECK (status<>'ACTIVE' OR (reviewed_by IS NOT NULL AND reviewed_by<>generated_by AND review_task_id IS NOT NULL)), \n\tFOREIGN KEY(source_knowledge_id) REFERENCES knowledge_documents (document_id), \n\tFOREIGN KEY(source_knowledge_version_id) REFERENCES knowledge_document_versions (knowledge_version_id), \n\tFOREIGN KEY(source_evidence_id) REFERENCES evidence_references (evidence_id), \n\tFOREIGN KEY(jurisdiction_id) REFERENCES jurisdictions (jurisdiction_id), \n\tFOREIGN KEY(review_task_id) REFERENCES admin_review_tasks (review_task_id)\n)\n\n",
    "\nCREATE TABLE knowledge_graph_edges (\n\tsource_knowledge_id VARCHAR(36) NOT NULL, \n\tsource_knowledge_version_id VARCHAR(36) NOT NULL, \n\tsource_evidence_id VARCHAR(36) NOT NULL, \n\tjurisdiction_id VARCHAR(36) NOT NULL, \n\tpayload_json JSON NOT NULL, \n\tgenerated_by VARCHAR(160) NOT NULL, \n\treviewed_by VARCHAR(160), \n\treview_task_id VARCHAR(36), \n\tderived BOOLEAN NOT NULL, \n\tlegal_applicability BOOLEAN NOT NULL, \n\tgraph_edge_id VARCHAR(36) NOT NULL, \n\tsource_node_id VARCHAR(36) NOT NULL, \n\ttarget_node_id VARCHAR(36) NOT NULL, \n\trelation_type_ref VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (graph_edge_id), \n\tCONSTRAINT ck_graph_edge_derived CHECK (derived AND NOT legal_applicability), \n\tCONSTRAINT ck_graph_edge_status CHECK (status IN ('DRAFT','ACTIVE','ARCHIVED')), \n\tCONSTRAINT ck_graph_edge_review CHECK (status<>'ACTIVE' OR (reviewed_by IS NOT NULL AND reviewed_by<>generated_by AND review_task_id IS NOT NULL)), \n\tFOREIGN KEY(source_knowledge_id) REFERENCES knowledge_documents (document_id), \n\tFOREIGN KEY(source_knowledge_version_id) REFERENCES knowledge_document_versions (knowledge_version_id), \n\tFOREIGN KEY(source_evidence_id) REFERENCES evidence_references (evidence_id), \n\tFOREIGN KEY(jurisdiction_id) REFERENCES jurisdictions (jurisdiction_id), \n\tFOREIGN KEY(review_task_id) REFERENCES admin_review_tasks (review_task_id), \n\tFOREIGN KEY(source_node_id) REFERENCES knowledge_graph_nodes (graph_node_id), \n\tFOREIGN KEY(target_node_id) REFERENCES knowledge_graph_nodes (graph_node_id), \n\tFOREIGN KEY(relation_type_ref) REFERENCES metadata_definitions (definition_id)\n)\n\n",
    "\nCREATE TABLE wiki_citations (\n\twiki_citation_id VARCHAR(36) NOT NULL, \n\twiki_version_id VARCHAR(36) NOT NULL, \n\tcitation_id VARCHAR(36) NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (wiki_citation_id), \n\tCONSTRAINT uq_wiki_citation UNIQUE (wiki_version_id, citation_id), \n\tFOREIGN KEY(wiki_version_id) REFERENCES wiki_versions (wiki_version_id), \n\tFOREIGN KEY(citation_id) REFERENCES citations (citation_id)\n)\n\n",
    "\nCREATE TABLE evidence_pack_items (\n\tevidence_item_id VARCHAR(36) NOT NULL, \n\tevidence_pack_id VARCHAR(36) NOT NULL, \n\tknowledge_version_id VARCHAR(36), \n\tchunk_id VARCHAR(36), \n\tstructure_node_id VARCHAR(36), \n\texternal_evidence_id VARCHAR(36), \n\tcitation_id VARCHAR(36) NOT NULL, \n\tpayload_json JSON NOT NULL, \n\ttenant_id VARCHAR(36) NOT NULL, \n\trecord_version INTEGER DEFAULT '1' NOT NULL, \n\tstatus VARCHAR(40) DEFAULT 'ACTIVE' NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tPRIMARY KEY (evidence_item_id), \n\tCONSTRAINT ck_evidence_exact_source_chain CHECK ((knowledge_version_id IS NOT NULL AND chunk_id IS NOT NULL AND structure_node_id IS NOT NULL AND external_evidence_id IS NULL) OR (knowledge_version_id IS NULL AND chunk_id IS NULL AND structure_node_id IS NULL AND external_evidence_id IS NOT NULL)), \n\tFOREIGN KEY(evidence_pack_id) REFERENCES evidence_packs (evidence_pack_id), \n\tFOREIGN KEY(knowledge_version_id) REFERENCES knowledge_document_versions (knowledge_version_id), \n\tFOREIGN KEY(chunk_id) REFERENCES knowledge_chunks (chunk_id), \n\tFOREIGN KEY(structure_node_id) REFERENCES knowledge_structure_nodes (structure_node_id), \n\tFOREIGN KEY(external_evidence_id) REFERENCES runtime_verified_external_evidence (external_evidence_id), \n\tFOREIGN KEY(citation_id) REFERENCES citations (citation_id)\n)\n\n",
    "CREATE INDEX ix_knowledge_sufficiency_policies_tenant_id ON knowledge_sufficiency_policies (tenant_id)",
    "CREATE INDEX ix_retrieval_policies_tenant_id ON retrieval_policies (tenant_id)",
    "CREATE INDEX ix_trusted_source_policies_tenant_id ON trusted_source_policies (tenant_id)",
    "CREATE INDEX ix_wiki_pages_tenant_id ON wiki_pages (tenant_id)",
    "CREATE INDEX ix_wiki_versions_tenant_id ON wiki_versions (tenant_id)",
    "CREATE INDEX ix_retrieval_runs_tenant_id ON retrieval_runs (tenant_id)",
    "CREATE INDEX ix_wiki_publish_records_tenant_id ON wiki_publish_records (tenant_id)",
    "CREATE INDEX ix_wiki_reviews_tenant_id ON wiki_reviews (tenant_id)",
    "CREATE INDEX ix_evidence_packs_tenant_id ON evidence_packs (tenant_id)",
    "CREATE INDEX ix_external_evidence_candidates_tenant_id ON external_evidence_candidates (tenant_id)",
    "CREATE INDEX ix_external_evidence_validation_results_tenant_id ON external_evidence_validation_results (tenant_id)",
    "CREATE INDEX ix_knowledge_sufficiency_results_tenant_id ON knowledge_sufficiency_results (tenant_id)",
    "CREATE INDEX ix_runtime_verified_external_evidence_tenant_id ON runtime_verified_external_evidence (tenant_id)",
    "CREATE INDEX ix_wiki_source_bindings_tenant_id ON wiki_source_bindings (tenant_id)",
    "CREATE INDEX ix_knowledge_runtime_publications_tenant_id ON knowledge_runtime_publications (tenant_id)",
    "CREATE INDEX ix_knowledge_graph_nodes_tenant_id ON knowledge_graph_nodes (tenant_id)",
    "CREATE INDEX ix_knowledge_graph_edges_tenant_id ON knowledge_graph_edges (tenant_id)",
    "CREATE INDEX ix_wiki_citations_tenant_id ON wiki_citations (tenant_id)",
    "CREATE INDEX ix_evidence_pack_items_tenant_id ON evidence_pack_items (tenant_id)",
    "CREATE UNIQUE INDEX uq_retrieval_active_policy ON retrieval_policies(tenant_id,policy_id) WHERE lifecycle='ACTIVE'",
    "CREATE UNIQUE INDEX uq_sufficiency_active_policy ON knowledge_sufficiency_policies(tenant_id,policy_id) WHERE lifecycle='ACTIVE'",
    "CREATE UNIQUE INDEX uq_trusted_source_active_policy ON trusted_source_policies(tenant_id,policy_id) WHERE lifecycle='ACTIVE'",
    "CREATE UNIQUE INDEX uq_wiki_active_version ON wiki_versions(tenant_id,wiki_page_id) WHERE lifecycle='ACTIVE'",
]
TABLES = [
    "knowledge_sufficiency_policies",
    "retrieval_policies",
    "trusted_source_policies",
    "wiki_pages",
    "wiki_versions",
    "retrieval_runs",
    "wiki_publish_records",
    "wiki_reviews",
    "evidence_packs",
    "external_evidence_candidates",
    "external_evidence_validation_results",
    "knowledge_sufficiency_results",
    "runtime_verified_external_evidence",
    "wiki_source_bindings",
    "knowledge_runtime_publications",
    "knowledge_graph_nodes",
    "knowledge_graph_edges",
    "wiki_citations",
    "evidence_pack_items",
]


def upgrade():
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade():
    for table in reversed(TABLES):
        op.drop_table(table)
