import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
import zhCN from '/workspace/crossborder-compliance-agent/frontend/src/locales/zh-CN.json' with { type: 'json' };
import zhHK from '/workspace/crossborder-compliance-agent/frontend/src/locales/zh-HK.json' with { type: 'json' };
import enUS from '/workspace/crossborder-compliance-agent/frontend/src/locales/en-US.json' with { type: 'json' };
const catalogs = { 'zh-CN': zhCN, 'zh-HK': zhHK, 'en-US': enUS };
const manifest = JSON.parse(fs.readFileSync(process.env.M2A_UAT_MANIFEST!, 'utf8'));
for (const [locale, messages] of Object.entries(catalogs)) test(`Exact-main completion CTA and source trace in ${locale}`, async ({ page }) => {
  test.setTimeout(180000);
  const missingKeys: string[] = [];
  page.on('console', message => { if (message.text().includes('I18N_MISSING_KEY')) missingKeys.push(message.text()); });
  const values = manifest.INTAKE.intake;
  await page.addInitScript(x => localStorage.setItem('stage1-alpha.ui-locale', x), locale);
  expect((await page.request.post('/m0-demo/login', { data: { persona: 'INTAKE' } })).status()).toBe(200);
  await page.goto('/intake');
  await page.getByLabel(messages['ui.m2a.projectName']).fill(`M2C formal results ${locale} ${Date.now()}`);
  await page.getByRole('button', { name: messages['ui.m2a.create'], exact: true }).click();
  const project = await page.getByTestId('intake-project-id').innerText();
  await page.getByLabel(messages['ui.m1.field.scenario']).selectOption(values.business_scenario);
  await page.getByLabel(messages['ui.m1.field.product']).selectOption(values.selected_products[0]);
  const next = () => page.getByRole('button', { name: messages['ui.m1.next'], exact: true }).click();
  await next();
  for (const field of ['source', 'destination'] as const) await page.getByLabel(messages[`ui.m1.field.${field}`]).selectOption(values.source_locations[0]);
  await page.getByLabel(messages['ui.m1.field.purpose']).fill(values.business_purpose);
  await page.getByLabel(messages['ui.m1.field.dataVolume']).fill('3');
  await next();
  await page.getByLabel(messages['ui.m1.field.description']).fill('Actual structured input and uploaded document');
  await page.getByRole('button', { name: messages['ui.m2a.save'], exact: true }).click();
  await expect(page.getByLabel(messages['ui.m1.field.scenario'])).toBeVisible();
  await next(); await next();
  // The existing policy rejects the same content hash in a different project.
  // Use a genuine DOCX archive with a unique project comment; parsed content
  // stays the same and provenance/content hash still describe the real binary.
  const binary = execFileSync('python', ['-c', "import io,sys,zipfile; b=io.BytesIO(open(sys.argv[1],'rb').read()); z=zipfile.ZipFile(b,'a'); z.comment=sys.argv[2].encode(); z.close(); sys.stdout.buffer.write(b.getvalue())", 'e2e/fixtures/m2c-intake.docx', project]);
  await page.getByLabel(messages['ui.m2b.select']).setInputFiles({ name: 'm2c-intake.docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: binary });
  await page.getByRole('button', { name: messages['ui.m2b.upload'], exact: true }).click();
  await expect(page.getByTestId('document-input')).toContainText('m2c-intake.docx');
  await page.reload(); await next(); await next();
  await expect(page.getByTestId('document-input')).toContainText(messages['ui.m2b.stored']);
  await page.getByRole('button', { name: messages['ui.m2b.parse'], exact: true }).click();
  await expect(page.getByTestId('document-input')).toContainText(messages['ui.m2b.parsed']);
  const docs = await (await page.request.get(`/api/v1/projects/${project}/intake/documents`)).json();
  expect(docs.items).toHaveLength(1); expect(docs.items[0].parse_run_id).toBeTruthy();
  await next(); await page.getByRole('checkbox', { name: messages['ui.m1.confirmFacts'] }).check();
  await page.getByRole('button', { name: messages['ui.m2a.confirmStart'], exact: true }).click();
  const run = await page.getByTestId('workflow-run-id').innerText();
  const confirmed = await (await page.request.get(`/api/v1/projects/${project}/intake`)).json();
  const view = await (await page.request.get(`/api/v1/workflows/${run}`)).json();
  expect(view.status).toBe('COMPLETED'); expect(view.project_id).toBe(project); expect(view.analysis_snapshot_id).toBe(confirmed.analysis_snapshot_id);
  expect(view.result_refs.applicability).toHaveLength(1);
  const pinned = await (await page.request.get(`/api/v1/projects/${project}/intake/documents`)).json();
  expect(pinned.items[0].document_version_id).toBe(docs.items[0].document_version_id); expect(pinned.items[0].parse_run_id).toBe(docs.items[0].parse_run_id);
  const resultPath = `/api/v1/workflows/${run}/stage1-result`;
  const formal = await (await page.request.get(resultPath)).json();
  expect(formal.workflow_run_id).toBe(run); expect(formal.analysis_snapshot_id).toBe(confirmed.analysis_snapshot_id);
  expect(formal.cross_border.items[0].status).toBe('DIRECT_TRANSFER_ALLOWED');
  expect(formal.document_requirements.items[0].requirement_level).toBe('REQUIRED');
  expect(formal.documents[0].document_version_id).toBe(docs.items[0].document_version_id);
  expect(formal.documents[0].parse_run_id).toBe(docs.items[0].parse_run_id);
  expect(formal.generation_available).toBe(false);
  expect(formal.mode).toBe('DATA_AWARE'); expect(formal.data_items).toHaveLength(1); expect(formal.classification).toHaveLength(1);
  expect(formal.cross_border.data_item_ids).toContain(formal.data_items[0].data_item_id);
  await page.getByRole('link', { name: messages['ui.m2c.openWorkspace'], exact: true }).click();
  await expect(page.getByTestId('stage1-run-id')).toHaveText(run, { timeout: 60000 });
  await expect(page.getByTestId('stage1-snapshot-id')).toHaveText(confirmed.analysis_snapshot_id, { timeout: 60000 });
  await expect(page.getByRole('img', {name:messages['ui.m2c.transferMap']})).toBeVisible();
  expect(await page.locator('.result-layout').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(243, 245, 249)');
  expect(await page.locator('.sidebar').evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(11, 16, 32)');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(page.viewportSize()!.width);
  await expect(page.getByText(messages['ui.m2c.pathNotice'],{exact:true})).toBeVisible();
  await page.getByRole('button',{name:messages['ui.m2c.legalEvidence'],exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByText(formal.legal_basis[0].official_source,{exact:true})).toBeVisible();
  await page.getByRole('dialog').locator('tbody button').first().click();
  await expect(page.locator('.source-excerpt')).toBeVisible();
  await page.keyboard.press('Escape');
  await page.keyboard.press('Escape');
  await page.getByRole('button',{name:messages['ui.m2c.chooseDocuments'],exact:true}).click();
  await expect(page.getByText(messages['ui.m2c.stage2Unavailable'],{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByTestId('stage1-run-id')).toHaveText(run, { timeout: 60000 });
  expect(await (await page.request.get(resultPath)).json()).toEqual(formal);
  for (const key of ['workflow', 'transferMap', 'risk', 'path', 'inventory', 'requirements']) {
    await expect(page.locator('.ant-card-head-title').filter({ hasText: messages[`ui.m2c.${key}` as keyof typeof messages] }).first()).toBeVisible();
  }
  await expect(page.locator('.stage1-kpis')).toBeVisible();
  const writes: string[] = [];
  page.on('request', request => { if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method()) && request.url().includes('/api/')) writes.push(request.url()); });
  await page.getByRole('button', { name: messages['ui.m2c.finish'], exact: true }).click();
  await expect(page.getByText(messages['ui.m2c.finished'], { exact: true })).toBeVisible();
  expect(await (await page.request.get(resultPath)).json()).toEqual(formal);
  expect(writes).toEqual([]);
  expect(missingKeys).toEqual([]);
  await page.screenshot({ path: `/workspace/m2c-main-control/browser-tests/results/completion-${locale}.png`, fullPage: true });
});
