import { test, expect, type Page } from '@playwright/test';
import fs from 'node:fs';
import zhCN from '../src/locales/zh-CN.json' with { type: 'json' };
import zhHK from '../src/locales/zh-HK.json' with { type: 'json' };
import enUS from '../src/locales/en-US.json' with { type: 'json' };
const catalogs = { 'zh-CN': zhCN, 'zh-HK': zhHK, 'en-US': enUS };
type Locale = keyof typeof catalogs;
const manifestPath = process.env.M2A_UAT_MANIFEST;
const manifest = manifestPath ? JSON.parse(fs.readFileSync(manifestPath, 'utf8')) : undefined;
const t = (locale: Locale, key: keyof typeof enUS) => catalogs[locale][key];
async function next(page: Page, locale: Locale) { await page.getByRole('button', { name: t(locale, 'ui.m1.next'), exact: true }).click(); }
for (const locale of Object.keys(catalogs) as Locale[]) test(`new persisted project, refresh, exact snapshot and canonical START/READ in ${locale}`, async ({ page }) => {
  test.setTimeout(120000);
  expect(manifest).toBeDefined();
  const values = manifest.INTAKE.intake;
  await page.addInitScript(value => localStorage.setItem('stage1-alpha.ui-locale', value), locale);
  const login = await page.request.post('/m0-demo/login', { data: { persona: 'INTAKE' } });
  expect(login.status()).toBe(200); expect((await login.json()).contexts).toEqual([]);
  await page.goto('/intake');
  await page.getByLabel(t(locale, 'ui.m2a.projectName')).fill(`Browser intake ${locale} ${Date.now()}`);
  await page.getByRole('button', { name: t(locale, 'ui.m2a.create'), exact: true }).click();
  const project = await page.getByTestId('intake-project-id').innerText();
  expect(new URL(page.url()).searchParams.get('project_id')).toBe(project);
  await expect(page.getByLabel(t(locale, 'ui.m1.field.scenario'))).toBeEnabled();
  await page.getByLabel(t(locale, 'ui.m1.field.scenario')).selectOption(values.business_scenario);
  await page.getByLabel(t(locale, 'ui.m1.field.product')).selectOption(values.selected_products[0]);
  await next(page, locale);
  for (const field of ['source', 'destination']) await page.getByLabel(t(locale, `ui.m1.field.${field}` as keyof typeof enUS)).selectOption(values.source_locations[0]);
  await page.getByLabel(t(locale, 'ui.m1.field.purpose')).fill(values.business_purpose);
  await page.getByLabel(t(locale, 'ui.m1.field.dataVolume')).fill('3');
  await next(page, locale);
  await page.getByLabel(t(locale, 'ui.m1.field.description')).fill('Structured manual scenario');
  await page.getByRole('button', { name: t(locale, 'ui.m2a.save'), exact: true }).click();
  await expect(page.getByLabel(t(locale, 'ui.m1.field.scenario'))).toHaveValue(values.business_scenario);
  await page.reload();
  await expect(page.getByTestId('intake-project-id')).toHaveText(project);
  await expect(page.getByLabel(t(locale, 'ui.m1.field.product'))).toHaveValue(values.selected_products[0]);
  await next(page, locale);
  await expect(page.getByLabel(t(locale, 'ui.m1.field.dataVolume'))).toHaveValue('3');
  await page.getByLabel(t(locale, 'ui.m1.field.flowDescription')).fill('Updated actual flow description');
  await page.getByRole('button', { name: t(locale, 'ui.m2a.save'), exact: true }).click();
  await expect(page.getByLabel(t(locale, 'ui.m1.field.scenario'))).toBeVisible();
  const draft = await (await page.request.get(`/api/v1/projects/${project}/intake`)).json();
  expect(draft.status).toBe('DRAFT'); expect(draft.version).toBe(3);
  expect(draft.analysis_snapshot_id).toBeNull();
  await next(page, locale); await next(page, locale); await next(page, locale);
  await page.getByRole('checkbox', { name: t(locale, 'ui.m1.confirmFacts') }).check();
  await page.getByRole('button', { name: t(locale, 'ui.m2a.confirmStart'), exact: true }).click();
  const run = await page.getByTestId('workflow-run-id').innerText();
  const confirmed = await (await page.request.get(`/api/v1/projects/${project}/intake`)).json();
  const view = await (await page.request.get(`/api/v1/workflows/${run}`)).json();
  expect(confirmed.status).toBe('CONFIRMED'); expect(confirmed.version).toBe(3);
  expect(view.status).toBe('COMPLETED'); expect(view.project_id).toBe(project);
  expect(view.analysis_snapshot_id).toBe(confirmed.analysis_snapshot_id);
  expect(view.workflow_run_id).toBe(confirmed.workflow_run_id);
  expect(view.result_refs.applicability).toHaveLength(1);
  const before = await page.request.post(`/api/v1/projects/${project}/snapshots/${view.analysis_snapshot_id}/workflow`, { data: {} });
  expect(await before.json()).toEqual(view);
  const nextLocale: Locale = locale === 'en-US' ? 'zh-HK' : 'en-US';
  await page.getByRole('combobox', { name: t(locale, 'ui.language') }).click();
  await page.getByTitle(t(locale, nextLocale === 'en-US' ? 'ui.localeEN' : 'ui.localeHK'), { exact: true }).click();
  await expect(page.getByTestId('workflow-run-id')).toHaveText(run);
  expect(await (await page.request.get(`/api/v1/workflows/${run}`)).json()).toEqual(view);
  await page.screenshot({ path: `test-results/m2a-${locale}.png`, fullPage: true });
});
