import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import zhCN from '../src/locales/zh-CN.json' with { type: 'json' };
import zhHK from '../src/locales/zh-HK.json' with { type: 'json' };
import enUS from '../src/locales/en-US.json' with { type: 'json' };
const catalogs = { 'zh-CN': zhCN, 'zh-HK': zhHK, 'en-US': enUS };
const manifest = JSON.parse(fs.readFileSync(process.env.M2A_UAT_MANIFEST!, 'utf8'));
for (const [locale, messages] of Object.entries(catalogs)) test(`real binary, pinned documents and canonical workflow in ${locale}`, async ({ page }) => {
  test.setTimeout(120000);
  const values = manifest.INTAKE.intake;
  await page.addInitScript(x => localStorage.setItem('stage1-alpha.ui-locale', x), locale);
  expect((await page.request.post('/m0-demo/login', { data: { persona: 'INTAKE' } })).status()).toBe(200);
  await page.goto('/intake');
  await page.getByLabel(messages['ui.m2a.projectName']).fill(`M2B real binary ${locale} ${Date.now()}`);
  await page.getByRole('button', { name: messages['ui.m2a.create'], exact: true }).click();
  const project = await page.getByTestId('intake-project-id').innerText();
  await page.getByLabel(messages['ui.m1.field.scenario']).selectOption(values.business_scenario);
  await page.getByLabel(messages['ui.m1.field.product']).selectOption(values.selected_products[0]);
  const next = () => page.getByRole('button', { name: messages['ui.m1.next'], exact: true }).click();
  await next();
  for (const field of ['source', 'destination'] as const) await page.getByLabel(messages[`ui.m1.field.${field}`]).selectOption(values.source_locations[0]);
  await page.getByLabel(messages['ui.m1.field.purpose']).fill(values.business_purpose);
  await page.getByLabel(messages['ui.m1.field.dataVolume']).fill('3');
  await next();
  await page.getByLabel(messages['ui.m1.field.description']).fill('Actual structured input and uploaded document');
  await page.getByRole('button', { name: messages['ui.m2a.save'], exact: true }).click();
  await expect(page.getByLabel(messages['ui.m1.field.scenario'])).toBeVisible();
  await next(); await next();
  await page.getByLabel(messages['ui.m2b.select']).setInputFiles({ name: 'actual-purpose.txt', mimeType: 'text/plain', buffer: Buffer.from(`Input for project ${project}\nPurpose: ${values.business_purpose}\n`) });
  await page.getByRole('button', { name: messages['ui.m2b.upload'], exact: true }).click();
  await expect(page.getByTestId('document-input')).toContainText('actual-purpose.txt');
  await page.reload(); await next(); await next();
  await expect(page.getByTestId('document-input')).toContainText(messages['ui.m2b.stored']);
  await page.getByRole('button', { name: messages['ui.m2b.parse'], exact: true }).click();
  await expect(page.getByTestId('document-input')).toContainText(messages['ui.m2b.parsed']);
  const docs = await (await page.request.get(`/api/v1/projects/${project}/intake/documents`)).json();
  expect(docs.items).toHaveLength(1); expect(docs.items[0].parse_run_id).toBeTruthy();
  await next(); await page.getByRole('checkbox', { name: messages['ui.m1.confirmFacts'] }).check();
  await page.getByRole('button', { name: messages['ui.m2a.confirmStart'], exact: true }).click();
  const run = await page.getByTestId('workflow-run-id').innerText();
  const confirmed = await (await page.request.get(`/api/v1/projects/${project}/intake`)).json();
  const view = await (await page.request.get(`/api/v1/workflows/${run}`)).json();
  expect(view.status).toBe('COMPLETED'); expect(view.project_id).toBe(project); expect(view.analysis_snapshot_id).toBe(confirmed.analysis_snapshot_id);
  expect(view.result_refs.applicability).toHaveLength(1);
  const pinned = await (await page.request.get(`/api/v1/projects/${project}/intake/documents`)).json();
  expect(pinned.items[0].document_version_id).toBe(docs.items[0].document_version_id); expect(pinned.items[0].parse_run_id).toBe(docs.items[0].parse_run_id);
  await page.screenshot({ path: `test-results/m2b-${locale}.png`, fullPage: true });
});
