from __future__ import annotations

from typing import Protocol
from uuid import UUID

from crossborder_compliance.domain.context_resolution import (
    BusinessFact, CandidateResolution, ContextConflict, ContextResolutionResult,
    DataFlowEdgeContext, DataFlowNodeContext, DataItemDeduplicationResult,
    DataItemResolutionDetail, DeviceContext, JurisdictionContext,
    JurisdictionResolution, PartyCandidate, PartyResolution, ProductContext,
    ProductContextCandidate, ProductScopeResolution, ScenarioContext,
    ScenarioResolution, SystemContext,
)


class SemanticResolutionPort(Protocol):
    """AI/semantic extension boundary. Implementations return suggestions only."""
    def suggest(self, *, subject_type: str, payload: dict[str, object]) -> dict[str, object]: ...


class CandidateSimilarityPort(Protocol):
    """Similarity output is candidate evidence and must never directly merge formal DataItems."""
    def candidate_similarity(self, *, left: dict[str, object], right: dict[str, object]) -> float | None: ...


class ContextResolutionRepositoryPort(Protocol):
    def project_exists(self, project_id: UUID) -> bool: ...
    def metadata_definition(self, definition_id: UUID) -> dict[str, object] | None: ...
    def metadata_definition_by_code(self, *, kind: str, code: str) -> dict[str, object] | None: ...
    def list_candidate_facts(self, project_id: UUID) -> list[dict[str, object]]: ...
    def list_candidate_items(self, project_id: UUID) -> list[dict[str, object]]: ...
    def list_candidate_flow_nodes(self, project_id: UUID) -> list[dict[str, object]]: ...
    def list_candidate_flow_edges(self, project_id: UUID) -> list[dict[str, object]]: ...
    def save_business_fact(self, fact: BusinessFact, candidate_ids: tuple[UUID, ...]) -> None: ...
    def save_candidate_resolution(self, resolution: CandidateResolution) -> None: ...
    def save_conflict(self, conflict: ContextConflict) -> None: ...
    def resolve_conflict(self, conflict_id: UUID, *, resolution: dict[str, object], resolved_by: str, expected_record_version: int) -> dict[str, object]: ...
    def list_conflicts(self, project_id: UUID) -> list[dict[str, object]]: ...
    def save_product_context_candidate(self, candidate: ProductContextCandidate) -> None: ...
    def save_product_context(self, context: ProductContext) -> None: ...
    def save_product_scope_resolution(self, resolution: ProductScopeResolution) -> None: ...
    def save_scenario_context(self, context: ScenarioContext) -> None: ...
    def save_scenario_resolution(self, resolution: ScenarioResolution) -> None: ...
    def save_system_context(self, context: SystemContext) -> None: ...
    def find_system_by_name(self, project_id: UUID, display_name: str) -> dict[str, object] | None: ...
    def save_device_context(self, context: DeviceContext) -> None: ...
    def save_party_candidate(self, candidate: PartyCandidate) -> None: ...
    def save_party_resolution(self, resolution: PartyResolution) -> None: ...
    def find_project_party_by_name(self, project_id: UUID, display_name: str) -> dict[str, object] | None: ...
    def create_formal_data_item(self, *, project_id: UUID, canonical_name: str, description: str | None, source_document_version_id: UUID | None, source_trace_id: UUID, detail: DataItemResolutionDetail) -> UUID: ...
    def attach_candidate_to_data_item(self, *, data_item_id: UUID, candidate_id: UUID, source_trace_ids: tuple[UUID, ...]) -> None: ...
    def save_dedup_result(self, result: DataItemDeduplicationResult) -> None: ...
    def ensure_data_group(self, *, project_id: UUID, name: str, grouping_reason: str, data_item_ids: tuple[UUID, ...]) -> UUID: ...
    def bind_data_item_product(self, *, data_item_id: UUID, product_domain_definition_id: UUID | None, product_definition_id: UUID | None, relationship_type: str, confidence: float, source_trace_ids: tuple[UUID, ...]) -> UUID: ...
    def save_jurisdiction_context(self, context: JurisdictionContext) -> None: ...
    def find_jurisdiction_context_by_input(self, project_id: UUID, input_value: str) -> dict[str, object] | None: ...
    def save_jurisdiction_resolution(self, resolution: JurisdictionResolution) -> None: ...
    def jurisdiction_exists(self, jurisdiction_id: UUID) -> bool: ...
    def create_formal_flow_node(self, *, project_id: UUID, node_type: str, display_name: str, jurisdiction_id: UUID | None, detail: DataFlowNodeContext) -> UUID: ...
    def create_formal_flow_edge(self, *, project_id: UUID, source_node_id: UUID, target_node_id: UUID, flow_type: str, detail: DataFlowEdgeContext) -> UUID: ...
    def link_data_item_flow(self, *, data_item_id: UUID, flow_edge_id: UUID, relationship_type: str, source_trace_ids: tuple[UUID, ...], confidence: float) -> UUID: ...
    def formal_data_item_by_candidate(self, candidate_id: UUID) -> UUID | None: ...
    def create_review_task(self, *, workflow_run_id: UUID, object_type: str, object_id: UUID, reason: str, idempotency_key: str) -> UUID: ...
    def start_context_run(self, project_id: UUID) -> dict[str, object]: ...
    def finish_context_run(self, context_resolution_run_id: UUID, *, statistics: dict[str, int], confidence: float) -> None: ...
    def get_context_resolution(self, project_id: UUID) -> ContextResolutionResult | None: ...
    def get_business_context(self, project_id: UUID) -> list[dict[str, object]]: ...
    def get_product_context(self, project_id: UUID) -> list[dict[str, object]]: ...
    def get_scenario_context(self, project_id: UUID) -> list[dict[str, object]]: ...
    def get_systems(self, project_id: UUID) -> list[dict[str, object]]: ...
    def get_devices(self, project_id: UUID) -> list[dict[str, object]]: ...
    def get_parties(self, project_id: UUID) -> list[dict[str, object]]: ...
    def get_data_items(self, project_id: UUID) -> list[dict[str, object]]: ...
    def get_data_groups(self, project_id: UUID) -> list[dict[str, object]]: ...
    def get_data_flows(self, project_id: UUID) -> dict[str, list[dict[str, object]]]: ...
    def get_jurisdiction_context(self, project_id: UUID) -> list[dict[str, object]]: ...
    def aggregate_statistics(self, project_id: UUID) -> dict[str, int]: ...
    def pin_snapshot_context(self, *, analysis_snapshot_id: UUID, project_id: UUID, context_resolution_run_id: UUID) -> None: ...
