from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol
from uuid import UUID

from crossborder_compliance.domain.document_intelligence import (
    BusinessFactCandidate,
    CandidateDataFlowEdge,
    CandidateDataFlowNode,
    CandidateDataItem,
    CandidateDiagramResult,
    CanonicalStructureNode,
    CrossDocumentLink,
    DocumentAnalysisSummary,
    DocumentParseQualityResult,
    ParsedDocument,
    SourceTraceRef,
)


class ObjectStoragePort(Protocol):
    def put(self, *, object_key: str, content: bytes, content_type: str) -> str: ...
    def get(self, storage_ref: str) -> bytes: ...


class MalwareScanPort(Protocol):
    def scan(self, *, content: bytes, filename: str) -> bool: ...


class OCRPort(Protocol):
    def extract(self, *, content: bytes, mime_type: str) -> list[dict[str, object]]: ...


class VisionDiagramPort(Protocol):
    def analyze(self, *, content: bytes, mime_type: str) -> CandidateDiagramResult: ...


class DocumentParserPort(Protocol):
    parser_name: str
    parser_version: str
    def supports(self, *, mime_type: str, filename: str) -> bool: ...
    def parse(self, *, document_version_id: UUID, content: bytes, filename: str, mime_type: str) -> ParsedDocument: ...


class TaskQueuePort(Protocol):
    def enqueue(self, *, task_id: UUID, task_type: str) -> None: ...


class DocumentIntelligenceRepositoryPort(Protocol):
    def create_document_version(self, *, project_id: UUID, filename: str, mime_type: str, size_bytes: int, content_hash: str, storage_ref: str) -> dict[str, object]: ...
    def add_document_version(self, *, document_id: UUID, filename: str, mime_type: str, size_bytes: int, content_hash: str, storage_ref: str) -> dict[str, object]: ...
    def get_document_version(self, document_version_id: UUID) -> dict[str, object] | None: ...
    def create_parse_task(self, *, document_version_id: UUID, idempotency_key: str, parser_profile_id: str) -> dict[str, object]: ...
    def get_parse_task(self, task_id: UUID) -> dict[str, object] | None: ...
    def set_parse_task_status(self, task_id: UUID, status: str, *, error_code: str | None = None) -> None: ...
    def create_parse_run(self, *, document_version_id: UUID, parser_profile_id: str, parser_name: str, parser_version: str) -> dict[str, object]: ...
    def finish_parse_run(self, parse_run_id: UUID, *, status: str, native_parse_used: bool, ocr_used: bool, vision_used: bool, counts: dict[str, int], quality_score: float | None, warning_count: int, error_code: str | None, language: str | None) -> None: ...
    def list_parse_runs(self, document_version_id: UUID) -> list[dict[str, object]]: ...
    def get_parse_run(self, parse_run_id: UUID) -> dict[str, object] | None: ...
    def replace_structure(self, parse_run_id: UUID, nodes: Iterable[CanonicalStructureNode]) -> list[SourceTraceRef]: ...
    def get_source_trace(self, source_trace_ref_id: UUID) -> SourceTraceRef | None: ...
    def list_structure(self, parse_run_id: UUID) -> list[dict[str, object]]: ...
    def save_quality(self, result: DocumentParseQualityResult) -> None: ...
    def get_quality(self, parse_run_id: UUID) -> dict[str, object] | None: ...
    def save_fact(self, parse_run_id: UUID, fact: BusinessFactCandidate) -> None: ...
    def save_candidate_item(self, parse_run_id: UUID, item: CandidateDataItem) -> None: ...
    def save_candidate_flow_node(self, parse_run_id: UUID, node: CandidateDataFlowNode) -> None: ...
    def save_candidate_flow_edge(self, parse_run_id: UUID, edge: CandidateDataFlowEdge) -> None: ...
    def list_facts(self, parse_run_id: UUID) -> list[dict[str, object]]: ...
    def list_candidate_items(self, parse_run_id: UUID) -> list[dict[str, object]]: ...
    def list_candidate_flows(self, parse_run_id: UUID) -> dict[str, list[dict[str, object]]]: ...
    def save_cross_document_link(self, project_id: UUID, link: CrossDocumentLink) -> None: ...
    def pin_parse_run(self, *, analysis_snapshot_id: UUID, document_version_id: UUID, parse_run_id: UUID) -> None: ...
    def aggregate_project_summary(self, project_id: UUID) -> DocumentAnalysisSummary: ...
