from collections.abc import Iterator
from typing import Protocol
from uuid import UUID

from crossborder_compliance.domain.llm_gateway import (
    AuthorizedInput,
    DetectionResult,
    GatewayAuditEvent,
    InputReference,
    LLMRequest,
    LLMResult,
    LLMStreamEvent,
    ModelCandidate,
    ModelUsagePolicy,
    ProviderInput,
    ProviderResult,
)
from crossborder_compliance.domain.security import RepositoryContext


class LLMServicePort(Protocol):
    def chat(self, request: LLMRequest) -> LLMResult: ...
    def chat_stream(self, request: LLMRequest) -> Iterator[LLMStreamEvent]: ...
    def structured_output(self, request: LLMRequest) -> LLMResult: ...
    def embedding(self, request: LLMRequest) -> LLMResult: ...
    def rerank(self, request: LLMRequest) -> LLMResult: ...
    def count_tokens(self, request: LLMRequest) -> LLMResult: ...
    def health_check(self, request: LLMRequest) -> LLMResult: ...


class AuthorizedInputSourcePort(Protocol):
    def load(
        self, context: RepositoryContext, project_id: UUID, refs: tuple[InputReference, ...]
    ) -> tuple[AuthorizedInput, ...]: ...


class LLMConfigurationPort(Protocol):
    def authorize(self, request: LLMRequest) -> None: ...
    def policies(self, request: LLMRequest) -> tuple[ModelUsagePolicy, ...]: ...
    def models(self, request: LLMRequest) -> tuple[ModelCandidate, ...]: ...
    def pin_models(self, request: LLMRequest, models: tuple[ModelCandidate, ...]) -> None: ...
    def prompt(self, request: LLMRequest) -> str | None: ...
    def revalidate(self, request: LLMRequest, model: ModelCandidate) -> None: ...


class ModelProviderAdapterPort(Protocol):
    supported_operations: frozenset

    def execute(self, model: ModelCandidate, payload: ProviderInput) -> ProviderResult: ...
    def stream(self, model: ModelCandidate, payload: ProviderInput) -> Iterator[str]: ...


class SensitiveDetectionPort(Protocol):
    def detect(self, texts: tuple[str, ...]) -> DetectionResult: ...


class GatewayAuditPort(Protocol):
    def record(self, event: GatewayAuditEvent) -> None: ...


class SecretResolverPort(Protocol):
    def resolve(self, secret_ref: str) -> str: ...
