"""Control-plane extensions to existing provider/model and secret authorities."""

from typing import Protocol

from crossborder_compliance.application.llm_gateway_ports import SecretResolverPort


class SecretStorePort(SecretResolverPort, Protocol):
    def put(self, value: str) -> str: ...


class ModelControlRepositoryPort(Protocol):
    def bind_invocation_prompt(self, version_id, purpose) -> dict: ...
    def list_providers(self) -> list[dict]: ...
    def save_provider(self, request, secret_ref: str | None) -> dict: ...
    def transition(self, kind: str, version_id, request) -> dict: ...
    def list_models(self, provider_id) -> list[dict]: ...
    def save_model(self, provider_id, request) -> dict: ...
    def set_enabled(self, kind: str, identity, enabled: bool, expected_version: int) -> dict: ...
