from __future__ import annotations
from typing import Protocol
from uuid import UUID
from crossborder_compliance.domain.contracts import WorkflowEventDTO

class RuntimeOperationsPort(Protocol):
    def ensure_review_task(self, *, workflow_run_id: UUID, tenant_id: UUID, idempotency_key: str,
                           review_type: str = "PHASE1A_SMOKE_REVIEW",
                           reason: str = "Verify durable interrupt/resume") -> UUID: ...
    def resolve_review(self, review_id: UUID, decision: dict[str, object]) -> None: ...
    def record_event(self, tenant_id: UUID, event: WorkflowEventDTO) -> None: ...
    def mark_review_required(self, workflow_run_id: UUID) -> None: ...
    def mark_resumed(self, workflow_run_id: UUID) -> None: ...
    def mark_completed(self, workflow_run_id: UUID, tenant_id: UUID, snapshot_id: UUID) -> None: ...
    def status(self, workflow_run_id: UUID) -> str: ...
    def set_status(self, workflow_run_id: UUID, status: str) -> None: ...
    def workflow_events(self, workflow_run_id: UUID, tenant_id: UUID) -> list[WorkflowEventDTO]: ...
