from __future__ import annotations

from collections.abc import Iterable
from typing import Generic, Protocol, TypeVar
from uuid import UUID

T = TypeVar("T")


class RegistryPort(Protocol, Generic[T]):
    def get(self, object_id: UUID) -> T | None: ...
    def list(self) -> list[T]: ...
    def resolve(self, **criteria: object) -> T | None: ...
    def refresh(self) -> None: ...
    def version(self) -> str: ...
    def health(self) -> dict[str, object]: ...


class RegistrySourcePort(Protocol):
    def load_active(self, kind: str) -> list[dict[str, object]]: ...
    def load_active_version(self, kind: str, definition_id: UUID) -> dict[str, object] | None: ...


class RegistrySyncEventRepositoryPort(Protocol):
    def pending(self, limit: int = 100) -> list[dict[str, object]]: ...
    def mark_applied(self, event_id: UUID) -> None: ...
    def mark_retry(self, event_id: UUID, error: str) -> None: ...


class SnapshotRegistryPinRepositoryPort(Protocol):
    def add_pin(
        self,
        *,
        analysis_snapshot_id: UUID,
        pin_type: str,
        logical_key: str,
        object_id: UUID,
        version_id: UUID,
        version_no: int,
    ) -> None: ...
    def list_pins(self, analysis_snapshot_id: UUID) -> list[dict[str, object]]: ...


class AdminMetadataRepositoryPort(Protocol):
    def create_definition(self, *, kind: str, code: str, display_name: str, parent_definition_id: UUID | None = None) -> dict[str, object]: ...
    def create_version(self, *, definition_id: UUID, payload: dict[str, object], effective_from=None, effective_to=None) -> dict[str, object]: ...
    def update_draft(self, version_id: UUID, *, payload: dict[str, object], expected_record_version: int) -> dict[str, object]: ...
    def transition(self, version_id: UUID, *, target_status: str, actor_id: str, expected_record_version: int) -> dict[str, object]: ...
    def history(self, definition_id: UUID) -> list[dict[str, object]]: ...
    def impact_preview(self, definition_id: UUID) -> dict[str, object]: ...
