from typing import Protocol

from crossborder_compliance.domain.retrieval import (
    ExternalEvidenceCandidate,
    KnowledgeSufficiencyResult,
    LexicalRetrievalResult,
    RetrievalCandidate,
    RetrievalSearchPlan,
    TrustedSourcePolicy,
    VectorRetrievalResult,
)


class LexicalRetrieverPort(Protocol):
    def retrieve(self, query_text: str, plan: RetrievalSearchPlan) -> LexicalRetrievalResult: ...


class VectorRetrieverPort(Protocol):
    def retrieve(
        self, vector: tuple[float, ...], plan: RetrievalSearchPlan
    ) -> VectorRetrievalResult: ...


class RerankerPort(Protocol):
    def rerank(
        self,
        query_text: str,
        candidates: tuple[RetrievalCandidate, ...],
        *,
        model_config_id: str | None,
    ) -> tuple[tuple[str, float], ...]: ...


class EvidenceGapQueryPlannerPort(Protocol):
    def plan(self, query_text: str, gaps: KnowledgeSufficiencyResult) -> tuple[str, ...]: ...


class AuthoritativeSourceDiscoveryPort(Protocol):
    def discover(
        self, queries: tuple[str, ...], policy: TrustedSourcePolicy
    ) -> tuple[ExternalEvidenceCandidate, ...]: ...


class WikiGenerationPort(Protocol):
    def generate(self, sources: tuple[dict, ...]) -> str: ...


class RetrievalRepositoryPort(Protocol):
    def resolve_policy(self, kind: str, policy_id: str, snapshot_id: str) -> dict: ...
    def prepare_search(self, scope, policy) -> RetrievalSearchPlan: ...
    def eligible_chunk_ids(
        self, plan: RetrievalSearchPlan, ids: tuple[str, ...]
    ) -> tuple[str, ...]: ...
    def formal_context(self, scope) -> dict: ...
    def begin_run(self, query, policy, plan) -> dict: ...
    def internal_evidence(self, run_id, plan, candidates) -> tuple: ...
    def complete_run(self, run_id, rag, traces, statistics) -> dict: ...
    def fail_run(self, run_id, reason_code: str) -> None: ...
    def saved_response(self, run_id) -> dict: ...
    def scoped_saved_response(self, run_id) -> dict: ...
    def model_config(self, config_id: str, capability: str) -> dict: ...
    def graph_neighbors(self, plan, candidates, limit: int) -> tuple: ...
    def source(self, source_id: str) -> dict: ...
    def saved_external(self, snapshot_id: str, source_id: str, trusted_policy_version: str): ...
    def external_candidate(self, run_id, candidate, validation) -> None: ...
    def persist_external(self, run_id, candidate, raw_content, payload, validation): ...
    def external_items(self, run_id, policy_version, records): ...
